# Generated automatically by compile.ps1. Do not edit.
INBUILT_KEYWORDS = {
'break', 'continue', 'else', 'for', 'if', 'in', 'none', 'null', 'return', 'while'
}
INBUILT_CONSTANTS = {
'e', 'pi'
}
INBUILT_FUNCTIONS = {
'abs', 'acos', 'acosh', 'all', 'angle', 'any', 'append', 'argmax', 'argmin', 'argsort', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'band', 'batch_shuffle', 'bitcount', 'bitwise_and', 'bitwise_not', 'bitwise_or', 'bitwise_xor', 'blur', 'bnot', 'bor', 'botk', 'botk_ind', 'botk_indices', 'bxor', 'cat', 'ceil', 'cellular', 'cellular_noise', 'cielab_to_rgb', 'clamp', 'cnt', 'concat', 'concatenate', 'conv', 'convolution', 'corr', 'correlation', 'cos', 'cosh', 'cosine_similarity', 'cossim', 'count', 'cov', 'crop', 'cross', 'cubic', 'cubic_ease', 'cumprod', 'cumsum', 'dilate', 'dist', 'distance', 'domain_warp', 'domain_warp_noise', 'dot', 'edge', 'elastic', 'elastic_ease', 'entropy', 'erf', 'erfinv', 'erode', 'exp', 'ezconv', 'ezconvolution', 'fft', 'find', 'flatten', 'flip', 'float', 'floor', 'flow_ang', 'flow_angle', 'flow_apply', 'flow_mag', 'flow_magnitude', 'flow_to_image', 'fract', 'gamma', 'gaussian', 'gelu', 'get_value', 'hist', 'histogram', 'hsv_to_rgb', 'ifft', 'int', 'int_to_rgb', 'interpolate_area', 'interpolate_linear', 'interpolate_nearest', 'interpolate_nearest_exact', 'join', 'length', 'lerp', 'linspace', 'ln', 'log', 'logspace', 'lower', 'map', 'matmul', 'mean', 'median', 'mode', 'moment', 'morph_close', 'morph_open', 'motion_mask', 'nan_to_num', 'noise', 'now', 'nvl', 'oklab_to_rgb', 'overlay', 'pad', 'percentile', 'perlin', 'perlin_noise', 'perm', 'permute', 'pinv', 'plasma', 'plasma_noise', 'popcnt', 'popcount', 'pow', 'prcnt', 'print', 'print_shape', 'pshp', 'quantile', 'quartil', 'quartile', 'rand', 'randb', 'randbeta', 'randc', 'rande', 'randg', 'randgumbel', 'randchi2', 'randl', 'randln', 'randn', 'random_bernoulli', 'random_beta', 'random_cauchy', 'random_exponential', 'random_gamma', 'random_gumbel', 'random_chi2', 'random_laplace', 'random_log_normal', 'random_normal', 'random_poisson', 'random_studentt', 'random_uniform', 'random_weibull', 'randp', 'randt', 'randu', 'randw', 'range', 'relu', 'remap', 'replace', 'reshape', 'rgb_to_cielab', 'rgb_to_hsv', 'rgb_to_int', 'rgb_to_oklab', 'ridged', 'ridged_noise', 'rife', 'roll', 'round', 'rshp', 'select', 'shape', 'shuffle', 'sigm', 'sign', 'sin', 'sine', 'sine_ease', 'sinh', 'smax', 'smin', 'smootherstep', 'smoothstep', 'snorm', 'softmax', 'softmin', 'softplus', 'sort', 'split', 'sqrt', 'stack_clear', 'stack_get', 'stack_has', 'stack_pop', 'stack_push', 'std', 'step', 'substr', 'substring', 'sum', 'swap', 'tan', 'tanh', 'tensor', 'text_image', 'timestamp', 'tmax', 'tmin', 'tnorm', 'topk', 'topk_ind', 'topk_indices', 'trim', 'turbulence', 'unique', 'upper', 'var', 'voronoi', 'voronoi_noise', 'where', 'worley'
}

INBUILT_FUNCTION_META = {
    'abs': {'min_args': 1, 'max_args': 1, 'snippet': 'abs()', 'description': 'abs(x) - applies per element absolute value function. Same as |x| for numbers.'},
    'acos': {'min_args': 1, 'max_args': 1, 'snippet': 'acos()', 'description': 'acos(x) - applies arcus cosinus function to value or each element of value'},
    'acosh': {'min_args': 1, 'max_args': 1, 'snippet': 'acosh()', 'description': 'acosh(x) - applies hyperbolic arcus cosinus function to value or each element of value'},
    'all': {'min_args': 1, 'max_args': 1, 'snippet': 'all()', 'description': ''},
    'angle': {'min_args': 1, 'max_args': 1, 'snippet': 'angle()', 'description': ''},
    'any': {'min_args': 1, 'max_args': 1, 'snippet': 'any()', 'description': ''},
    'append': {'min_args': 2, 'max_args': 2, 'snippet': 'append()', 'description': ''},
    'argmax': {'min_args': 1, 'max_args': 1, 'snippet': 'argmax()', 'description': ''},
    'argmin': {'min_args': 1, 'max_args': 1, 'snippet': 'argmin()', 'description': ''},
    'argsort': {'min_args': 1, 'max_args': 2, 'snippet': 'argsort()', 'description': ''},
    'asin': {'min_args': 1, 'max_args': 1, 'snippet': 'asin()', 'description': 'asin(x) - applies arcus sinus function to value or each element of value'},
    'asinh': {'min_args': 1, 'max_args': 1, 'snippet': 'asinh()', 'description': 'asinh(x) - applies hyperbolic arcus sinus function to value or each element of value'},
    'atan': {'min_args': 1, 'max_args': 1, 'snippet': 'atan()', 'description': 'atan(x) - applies arcus tangents function to value or each element of value'},
    'atan2': {'min_args': 2, 'max_args': 2, 'snippet': 'atan2()', 'description': ''},
    'atanh': {'min_args': 1, 'max_args': 1, 'snippet': 'atanh()', 'description': 'atanh(x) - applies hyperbolic arcus tangents function to value or each element of value'},
    'band': {'min_args': 2, 'max_args': 2, 'snippet': 'band()', 'description': ''},
    'batch_shuffle': {'min_args': 2, 'max_args': 2, 'snippet': 'batch_shuffle()', 'description': ''},
    'bitcount': {'min_args': 1, 'max_args': 1, 'snippet': 'bitcount()', 'description': ''},
    'bitwise_and': {'min_args': 2, 'max_args': 2, 'snippet': 'bitwise_and()', 'description': ''},
    'bitwise_not': {'min_args': 1, 'max_args': 1, 'snippet': 'bitwise_not()', 'description': ''},
    'bitwise_or': {'min_args': 2, 'max_args': 2, 'snippet': 'bitwise_or()', 'description': ''},
    'bitwise_xor': {'min_args': 2, 'max_args': 2, 'snippet': 'bitwise_xor()', 'description': ''},
    'blur': {'min_args': 2, 'max_args': 3, 'snippet': 'blur()', 'description': ''},
    'bnot': {'min_args': 1, 'max_args': 1, 'snippet': 'bnot()', 'description': ''},
    'bor': {'min_args': 2, 'max_args': 2, 'snippet': 'bor()', 'description': ''},
    'botk': {'min_args': 2, 'max_args': 2, 'snippet': 'botk()', 'description': ''},
    'botk_ind': {'min_args': 2, 'max_args': 2, 'snippet': 'botk_ind()', 'description': ''},
    'botk_indices': {'min_args': 2, 'max_args': 2, 'snippet': 'botk_indices()', 'description': ''},
    'bxor': {'min_args': 2, 'max_args': 2, 'snippet': 'bxor()', 'description': ''},
    'cat': {'min_args': 2, 'max_args': None, 'snippet': 'cat()', 'description': ''},
    'ceil': {'min_args': 1, 'max_args': 1, 'snippet': 'ceil()', 'description': ''},
    'cellular': {'min_args': 2, 'max_args': 5, 'snippet': 'cellular()', 'description': ''},
    'cellular_noise': {'min_args': 2, 'max_args': 5, 'snippet': 'cellular_noise()', 'description': ''},
    'cielab_to_rgb': {'min_args': 1, 'max_args': 3, 'snippet': 'cielab_to_rgb()', 'description': ''},
    'clamp': {'min_args': 3, 'max_args': 3, 'snippet': 'clamp()', 'description': ''},
    'cnt': {'min_args': 1, 'max_args': 1, 'snippet': 'cnt()', 'description': ''},
    'concat': {'min_args': 2, 'max_args': None, 'snippet': 'concat()', 'description': ''},
    'concatenate': {'min_args': 2, 'max_args': None, 'snippet': 'concatenate()', 'description': ''},
    'conv': {'min_args': 2, 'max_args': None, 'snippet': 'conv()', 'description': ''},
    'convolution': {'min_args': 2, 'max_args': None, 'snippet': 'convolution()', 'description': ''},
    'corr': {'min_args': 2, 'max_args': 2, 'snippet': 'corr()', 'description': ''},
    'correlation': {'min_args': 2, 'max_args': 2, 'snippet': 'correlation()', 'description': ''},
    'cos': {'min_args': 1, 'max_args': 1, 'snippet': 'cos()', 'description': 'cos(x) - applies cosinus function to value or each element of value'},
    'cosh': {'min_args': 1, 'max_args': 1, 'snippet': 'cosh()', 'description': 'cosh(x) - applies hyperbolic cosinus function to value or each element of value'},
    'cosine_similarity': {'min_args': 2, 'max_args': 2, 'snippet': 'cosine_similarity()', 'description': ''},
    'cossim': {'min_args': 2, 'max_args': 2, 'snippet': 'cossim()', 'description': ''},
    'count': {'min_args': 1, 'max_args': 1, 'snippet': 'count()', 'description': ''},
    'cov': {'min_args': 2, 'max_args': 2, 'snippet': 'cov()', 'description': ''},
    'crop': {'min_args': 3, 'max_args': 3, 'snippet': 'crop()', 'description': ''},
    'cross': {'min_args': 2, 'max_args': 2, 'snippet': 'cross()', 'description': ''},
    'cubic': {'min_args': 3, 'max_args': 3, 'snippet': 'cubic()', 'description': ''},
    'cubic_ease': {'min_args': 3, 'max_args': 3, 'snippet': 'cubic_ease()', 'description': ''},
    'cumprod': {'min_args': 1, 'max_args': 1, 'snippet': 'cumprod()', 'description': ''},
    'cumsum': {'min_args': 1, 'max_args': 1, 'snippet': 'cumsum()', 'description': ''},
    'dilate': {'min_args': 1, 'max_args': 2, 'snippet': 'dilate()', 'description': ''},
    'dist': {'min_args': 4, 'max_args': 4, 'snippet': 'dist()', 'description': ''},
    'distance': {'min_args': 4, 'max_args': 4, 'snippet': 'distance()', 'description': ''},
    'domain_warp': {'min_args': 4, 'max_args': 8, 'snippet': 'domain_warp()', 'description': ''},
    'domain_warp_noise': {'min_args': 4, 'max_args': 8, 'snippet': 'domain_warp_noise()', 'description': ''},
    'dot': {'min_args': 2, 'max_args': 2, 'snippet': 'dot()', 'description': ''},
    'edge': {'min_args': 1, 'max_args': 2, 'snippet': 'edge()', 'description': ''},
    'elastic': {'min_args': 3, 'max_args': 3, 'snippet': 'elastic()', 'description': ''},
    'elastic_ease': {'min_args': 3, 'max_args': 3, 'snippet': 'elastic_ease()', 'description': ''},
    'entropy': {'min_args': 1, 'max_args': 1, 'snippet': 'entropy()', 'description': ''},
    'erf': {'min_args': 1, 'max_args': 1, 'snippet': 'erf()', 'description': ''},
    'erfinv': {'min_args': 1, 'max_args': 1, 'snippet': 'erfinv()', 'description': ''},
    'erode': {'min_args': 1, 'max_args': 2, 'snippet': 'erode()', 'description': ''},
    'exp': {'min_args': 1, 'max_args': 1, 'snippet': 'exp()', 'description': 'exp(x) - applies e^x to value (per element)'},
    'ezconv': {'min_args': 2, 'max_args': None, 'snippet': 'ezconv()', 'description': ''},
    'ezconvolution': {'min_args': 2, 'max_args': None, 'snippet': 'ezconvolution()', 'description': ''},
    'fft': {'min_args': 1, 'max_args': 1, 'snippet': 'fft()', 'description': ''},
    'find': {'min_args': 2, 'max_args': 2, 'snippet': 'find()', 'description': ''},
    'flatten': {'min_args': 1, 'max_args': 1, 'snippet': 'flatten()', 'description': ''},
    'flip': {'min_args': 2, 'max_args': 2, 'snippet': 'flip()', 'description': ''},
    'float': {'min_args': 1, 'max_args': 1, 'snippet': 'float()', 'description': ''},
    'floor': {'min_args': 1, 'max_args': 1, 'snippet': 'floor()', 'description': ''},
    'flow_ang': {'min_args': 1, 'max_args': 1, 'snippet': 'flow_ang()', 'description': ''},
    'flow_angle': {'min_args': 1, 'max_args': 1, 'snippet': 'flow_angle()', 'description': ''},
    'flow_apply': {'min_args': 2, 'max_args': 2, 'snippet': 'flow_apply()', 'description': ''},
    'flow_mag': {'min_args': 1, 'max_args': 1, 'snippet': 'flow_mag()', 'description': ''},
    'flow_magnitude': {'min_args': 1, 'max_args': 1, 'snippet': 'flow_magnitude()', 'description': ''},
    'flow_to_image': {'min_args': 1, 'max_args': 1, 'snippet': 'flow_to_image()', 'description': ''},
    'fract': {'min_args': 1, 'max_args': 1, 'snippet': 'fract()', 'description': ''},
    'gamma': {'min_args': 1, 'max_args': 1, 'snippet': 'gamma()', 'description': ''},
    'gaussian': {'min_args': 2, 'max_args': 3, 'snippet': 'gaussian()', 'description': ''},
    'gelu': {'min_args': 1, 'max_args': 1, 'snippet': 'gelu()', 'description': ''},
    'get_value': {'min_args': 2, 'max_args': 2, 'snippet': 'get_value()', 'description': ''},
    'hist': {'min_args': 4, 'max_args': 4, 'snippet': 'hist()', 'description': ''},
    'histogram': {'min_args': 4, 'max_args': 4, 'snippet': 'histogram()', 'description': ''},
    'hsv_to_rgb': {'min_args': 1, 'max_args': 4, 'snippet': 'hsv_to_rgb()', 'description': ''},
    'ifft': {'min_args': 1, 'max_args': 2, 'snippet': 'ifft()', 'description': ''},
    'int': {'min_args': 1, 'max_args': 1, 'snippet': 'int()', 'description': ''},
    'int_to_rgb': {'min_args': 1, 'max_args': 1, 'snippet': 'int_to_rgb()', 'description': ''},
    'interpolate_area': {'min_args': 2, 'max_args': 2, 'snippet': 'interpolate_area()', 'description': ''},
    'interpolate_linear': {'min_args': 2, 'max_args': 2, 'snippet': 'interpolate_linear()', 'description': ''},
    'interpolate_nearest': {'min_args': 2, 'max_args': 2, 'snippet': 'interpolate_nearest()', 'description': ''},
    'interpolate_nearest_exact': {'min_args': 2, 'max_args': 2, 'snippet': 'interpolate_nearest_exact()', 'description': ''},
    'join': {'min_args': 1, 'max_args': 2, 'snippet': 'join()', 'description': ''},
    'length': {'min_args': 1, 'max_args': 1, 'snippet': 'length()', 'description': ''},
    'lerp': {'min_args': 3, 'max_args': 3, 'snippet': 'lerp()', 'description': ''},
    'linspace': {'min_args': 3, 'max_args': 3, 'snippet': 'linspace()', 'description': ''},
    'ln': {'min_args': 1, 'max_args': 1, 'snippet': 'ln()', 'description': 'ln(x) - applies natural logarithm to value (per element). Negative numbers return NaN (not a number)'},
    'log': {'min_args': 1, 'max_args': 1, 'snippet': 'log()', 'description': 'log(x) - applies base 10 logarithm to value (per element). Negative numbers return NaN (not a number)'},
    'logspace': {'min_args': 4, 'max_args': 4, 'snippet': 'logspace()', 'description': ''},
    'lower': {'min_args': 1, 'max_args': 1, 'snippet': 'lower()', 'description': ''},
    'map': {'min_args': 2, 'max_args': None, 'snippet': 'map()', 'description': ''},
    'matmul': {'min_args': 2, 'max_args': 2, 'snippet': 'matmul()', 'description': ''},
    'mean': {'min_args': 1, 'max_args': 1, 'snippet': 'mean()', 'description': ''},
    'median': {'min_args': 1, 'max_args': 1, 'snippet': 'median()', 'description': ''},
    'mode': {'min_args': 1, 'max_args': 1, 'snippet': 'mode()', 'description': ''},
    'moment': {'min_args': 3, 'max_args': 3, 'snippet': 'moment()', 'description': ''},
    'morph_close': {'min_args': 1, 'max_args': 2, 'snippet': 'morph_close()', 'description': ''},
    'morph_open': {'min_args': 1, 'max_args': 2, 'snippet': 'morph_open()', 'description': ''},
    'motion_mask': {'min_args': 1, 'max_args': 1, 'snippet': 'motion_mask()', 'description': ''},
    'nan_to_num': {'min_args': 4, 'max_args': 4, 'snippet': 'nan_to_num()', 'description': ''},
    'noise': {'min_args': 1, 'max_args': 2, 'snippet': 'noise()', 'description': ''},
    'now': {'min_args': 0, 'max_args': 0, 'snippet': 'now()', 'description': ''},
    'nvl': {'min_args': 4, 'max_args': 4, 'snippet': 'nvl()', 'description': ''},
    'oklab_to_rgb': {'min_args': 1, 'max_args': 3, 'snippet': 'oklab_to_rgb()', 'description': ''},
    'overlay': {'min_args': 3, 'max_args': 4, 'snippet': 'overlay()', 'description': ''},
    'pad': {'min_args': 2, 'max_args': 2, 'snippet': 'pad()', 'description': ''},
    'percentile': {'min_args': 2, 'max_args': 2, 'snippet': 'percentile()', 'description': ''},
    'perlin': {'min_args': 2, 'max_args': 5, 'snippet': 'perlin()', 'description': ''},
    'perlin_noise': {'min_args': 2, 'max_args': 5, 'snippet': 'perlin_noise()', 'description': ''},
    'perm': {'min_args': 2, 'max_args': 2, 'snippet': 'perm()', 'description': ''},
    'permute': {'min_args': 2, 'max_args': 2, 'snippet': 'permute()', 'description': ''},
    'pinv': {'min_args': 1, 'max_args': 1, 'snippet': 'pinv()', 'description': ''},
    'plasma': {'min_args': 2, 'max_args': 5, 'snippet': 'plasma()', 'description': ''},
    'plasma_noise': {'min_args': 2, 'max_args': 5, 'snippet': 'plasma_noise()', 'description': ''},
    'popcnt': {'min_args': 1, 'max_args': 1, 'snippet': 'popcnt()', 'description': ''},
    'popcount': {'min_args': 1, 'max_args': 1, 'snippet': 'popcount()', 'description': ''},
    'pow': {'min_args': 2, 'max_args': 2, 'snippet': 'pow()', 'description': ''},
    'prcnt': {'min_args': 2, 'max_args': 2, 'snippet': 'prcnt()', 'description': ''},
    'print': {'min_args': 1, 'max_args': 1, 'snippet': 'print()', 'description': ''},
    'print_shape': {'min_args': 1, 'max_args': 1, 'snippet': 'print_shape()', 'description': ''},
    'pshp': {'min_args': 1, 'max_args': 1, 'snippet': 'pshp()', 'description': ''},
    'quantile': {'min_args': 2, 'max_args': 2, 'snippet': 'quantile()', 'description': ''},
    'quartil': {'min_args': 2, 'max_args': 2, 'snippet': 'quartil()', 'description': ''},
    'quartile': {'min_args': 2, 'max_args': 2, 'snippet': 'quartile()', 'description': ''},
    'rand': {'min_args': 1, 'max_args': 2, 'snippet': 'rand()', 'description': ''},
    'randb': {'min_args': 2, 'max_args': 3, 'snippet': 'randb()', 'description': ''},
    'randbeta': {'min_args': 3, 'max_args': 4, 'snippet': 'randbeta()', 'description': ''},
    'randc': {'min_args': 3, 'max_args': 4, 'snippet': 'randc()', 'description': ''},
    'rande': {'min_args': 2, 'max_args': 3, 'snippet': 'rande()', 'description': ''},
    'randg': {'min_args': 3, 'max_args': 4, 'snippet': 'randg()', 'description': ''},
    'randgumbel': {'min_args': 3, 'max_args': 4, 'snippet': 'randgumbel()', 'description': ''},
    'randchi2': {'min_args': 2, 'max_args': 3, 'snippet': 'randchi2()', 'description': ''},
    'randl': {'min_args': 3, 'max_args': 4, 'snippet': 'randl()', 'description': ''},
    'randln': {'min_args': 3, 'max_args': 4, 'snippet': 'randln()', 'description': ''},
    'randn': {'min_args': 1, 'max_args': 2, 'snippet': 'randn()', 'description': ''},
    'random_bernoulli': {'min_args': 2, 'max_args': 3, 'snippet': 'random_bernoulli()', 'description': ''},
    'random_beta': {'min_args': 3, 'max_args': 4, 'snippet': 'random_beta()', 'description': ''},
    'random_cauchy': {'min_args': 3, 'max_args': 4, 'snippet': 'random_cauchy()', 'description': ''},
    'random_exponential': {'min_args': 2, 'max_args': 3, 'snippet': 'random_exponential()', 'description': ''},
    'random_gamma': {'min_args': 3, 'max_args': 4, 'snippet': 'random_gamma()', 'description': ''},
    'random_gumbel': {'min_args': 3, 'max_args': 4, 'snippet': 'random_gumbel()', 'description': ''},
    'random_chi2': {'min_args': 2, 'max_args': 3, 'snippet': 'random_chi2()', 'description': ''},
    'random_laplace': {'min_args': 3, 'max_args': 4, 'snippet': 'random_laplace()', 'description': ''},
    'random_log_normal': {'min_args': 3, 'max_args': 4, 'snippet': 'random_log_normal()', 'description': ''},
    'random_normal': {'min_args': 1, 'max_args': 2, 'snippet': 'random_normal()', 'description': ''},
    'random_poisson': {'min_args': 2, 'max_args': 3, 'snippet': 'random_poisson()', 'description': ''},
    'random_studentt': {'min_args': 2, 'max_args': 3, 'snippet': 'random_studentt()', 'description': ''},
    'random_uniform': {'min_args': 1, 'max_args': 2, 'snippet': 'random_uniform()', 'description': ''},
    'random_weibull': {'min_args': 3, 'max_args': 4, 'snippet': 'random_weibull()', 'description': ''},
    'randp': {'min_args': 2, 'max_args': 3, 'snippet': 'randp()', 'description': ''},
    'randt': {'min_args': 2, 'max_args': 3, 'snippet': 'randt()', 'description': ''},
    'randu': {'min_args': 1, 'max_args': 2, 'snippet': 'randu()', 'description': ''},
    'randw': {'min_args': 3, 'max_args': 4, 'snippet': 'randw()', 'description': ''},
    'range': {'min_args': 3, 'max_args': 3, 'snippet': 'range()', 'description': ''},
    'relu': {'min_args': 1, 'max_args': None, 'snippet': 'relu()', 'description': ''},
    'remap': {'min_args': 5, 'max_args': 5, 'snippet': 'remap()', 'description': ''},
    'replace': {'min_args': 3, 'max_args': 3, 'snippet': 'replace()', 'description': ''},
    'reshape': {'min_args': 2, 'max_args': 2, 'snippet': 'reshape()', 'description': ''},
    'rgb_to_cielab': {'min_args': 1, 'max_args': 3, 'snippet': 'rgb_to_cielab()', 'description': ''},
    'rgb_to_hsv': {'min_args': 1, 'max_args': 4, 'snippet': 'rgb_to_hsv()', 'description': ''},
    'rgb_to_int': {'min_args': 1, 'max_args': 3, 'snippet': 'rgb_to_int()', 'description': ''},
    'rgb_to_oklab': {'min_args': 1, 'max_args': 3, 'snippet': 'rgb_to_oklab()', 'description': ''},
    'ridged': {'min_args': 2, 'max_args': 5, 'snippet': 'ridged()', 'description': ''},
    'ridged_noise': {'min_args': 2, 'max_args': 5, 'snippet': 'ridged_noise()', 'description': ''},
    'rife': {'min_args': 4, 'max_args': 5, 'snippet': 'rife()', 'description': ''},
    'roll': {'min_args': 2, 'max_args': 3, 'snippet': 'roll()', 'description': ''},
    'round': {'min_args': 1, 'max_args': 1, 'snippet': 'round()', 'description': ''},
    'rshp': {'min_args': 2, 'max_args': 2, 'snippet': 'rshp()', 'description': ''},
    'select': {'min_args': 2, 'max_args': 2, 'snippet': 'select()', 'description': ''},
    'shape': {'min_args': 1, 'max_args': 1, 'snippet': 'shape()', 'description': ''},
    'shuffle': {'min_args': 2, 'max_args': 2, 'snippet': 'shuffle()', 'description': ''},
    'sigm': {'min_args': 1, 'max_args': 1, 'snippet': 'sigm()', 'description': ''},
    'sign': {'min_args': 1, 'max_args': 1, 'snippet': 'sign()', 'description': ''},
    'sin': {'min_args': 1, 'max_args': 1, 'snippet': 'sin()', 'description': 'sin(x) - applies sinus function to value or each element of value'},
    'sine': {'min_args': 3, 'max_args': 3, 'snippet': 'sine()', 'description': ''},
    'sine_ease': {'min_args': 3, 'max_args': 3, 'snippet': 'sine_ease()', 'description': ''},
    'sinh': {'min_args': 1, 'max_args': 1, 'snippet': 'sinh()', 'description': 'sinh(x) - applies hyperbolic sinus function to value or each element of value'},
    'smax': {'min_args': 1, 'max_args': None, 'snippet': 'smax()', 'description': ''},
    'smin': {'min_args': 1, 'max_args': None, 'snippet': 'smin()', 'description': ''},
    'smootherstep': {'min_args': 3, 'max_args': 3, 'snippet': 'smootherstep()', 'description': ''},
    'smoothstep': {'min_args': 3, 'max_args': 3, 'snippet': 'smoothstep()', 'description': ''},
    'snorm': {'min_args': 1, 'max_args': 1, 'snippet': 'snorm()', 'description': 'snorm(x) - frobenius norm of tensor'},
    'softmax': {'min_args': 1, 'max_args': 2, 'snippet': 'softmax()', 'description': ''},
    'softmin': {'min_args': 1, 'max_args': 2, 'snippet': 'softmin()', 'description': ''},
    'softplus': {'min_args': 1, 'max_args': 1, 'snippet': 'softplus()', 'description': ''},
    'sort': {'min_args': 1, 'max_args': 1, 'snippet': 'sort()', 'description': ''},
    'split': {'min_args': 1, 'max_args': 2, 'snippet': 'split()', 'description': ''},
    'sqrt': {'min_args': 1, 'max_args': 1, 'snippet': 'sqrt()', 'description': 'sqrt(x) - applies sqere root per element. Negative numbers return NaN (not a number)'},
    'stack_clear': {'min_args': 1, 'max_args': 1, 'snippet': 'stack_clear()', 'description': ''},
    'stack_get': {'min_args': 1, 'max_args': 1, 'snippet': 'stack_get()', 'description': ''},
    'stack_has': {'min_args': 1, 'max_args': 1, 'snippet': 'stack_has()', 'description': ''},
    'stack_pop': {'min_args': 1, 'max_args': 1, 'snippet': 'stack_pop()', 'description': ''},
    'stack_push': {'min_args': 2, 'max_args': 2, 'snippet': 'stack_push()', 'description': ''},
    'std': {'min_args': 1, 'max_args': 1, 'snippet': 'std()', 'description': ''},
    'step': {'min_args': 2, 'max_args': 2, 'snippet': 'step()', 'description': ''},
    'substr': {'min_args': 2, 'max_args': 3, 'snippet': 'substr()', 'description': ''},
    'substring': {'min_args': 2, 'max_args': 3, 'snippet': 'substring()', 'description': ''},
    'sum': {'min_args': 1, 'max_args': 1, 'snippet': 'sum()', 'description': ''},
    'swap': {'min_args': 4, 'max_args': 4, 'snippet': 'swap()', 'description': ''},
    'tan': {'min_args': 1, 'max_args': 1, 'snippet': 'tan()', 'description': 'tan(x) - applies tangents function to value or each element of value'},
    'tanh': {'min_args': 1, 'max_args': 1, 'snippet': 'tanh()', 'description': 'tanh(x) - applies hyperbolic tangents function to value or each element of value'},
    'tensor': {'min_args': 2, 'max_args': 3, 'snippet': 'tensor()', 'description': ''},
    'text_image': {'min_args': 3, 'max_args': 9, 'snippet': 'text_image()', 'description': ''},
    'timestamp': {'min_args': 0, 'max_args': 0, 'snippet': 'timestamp()', 'description': ''},
    'tmax': {'min_args': 2, 'max_args': 2, 'snippet': 'tmax()', 'description': 'tmax(x,y) - elementwise maximum of tensor or list. max(x,y) when inputs are floats'},
    'tmin': {'min_args': 2, 'max_args': 2, 'snippet': 'tmin()', 'description': ''},
    'tnorm': {'min_args': 1, 'max_args': 1, 'snippet': 'tnorm()', 'description': 'tnorm(x) - normalises tensor or list by multiplication such that sum(x^2)==1.0 for each slice. The slice is last dimension of the tensor.'},
    'topk': {'min_args': 2, 'max_args': 2, 'snippet': 'topk()', 'description': ''},
    'topk_ind': {'min_args': 2, 'max_args': 2, 'snippet': 'topk_ind()', 'description': ''},
    'topk_indices': {'min_args': 2, 'max_args': 2, 'snippet': 'topk_indices()', 'description': ''},
    'trim': {'min_args': 1, 'max_args': 1, 'snippet': 'trim()', 'description': ''},
    'turbulence': {'min_args': 2, 'max_args': 5, 'snippet': 'turbulence()', 'description': ''},
    'unique': {'min_args': 1, 'max_args': 1, 'snippet': 'unique()', 'description': ''},
    'upper': {'min_args': 1, 'max_args': 1, 'snippet': 'upper()', 'description': ''},
    'var': {'min_args': 1, 'max_args': 1, 'snippet': 'var()', 'description': ''},
    'voronoi': {'min_args': 2, 'max_args': 5, 'snippet': 'voronoi()', 'description': ''},
    'voronoi_noise': {'min_args': 2, 'max_args': 5, 'snippet': 'voronoi_noise()', 'description': ''},
    'where': {'min_args': 3, 'max_args': 3, 'snippet': 'where()', 'description': ''},
    'worley': {'min_args': 2, 'max_args': 5, 'snippet': 'worley()', 'description': ''},
}