// Generated automatically by compile.ps1. Do not edit.

export const KEYWORDS = new Set([
"break", "continue", "else", "for", "if", "in", "none", "null", "return", "while"
]);

export const CONSTANTS = new Set([
"e", "pi"
]);

export const FUNCTIONS = new Set([
"abs", "acos", "acosh", "all", "angle", "any", "append", "argmax", "argmin", "argsort", "asin", "asinh", "atan", "atan2", "atanh", "band", "batch_shuffle", "bitcount", "bitwise_and", "bitwise_not", "bitwise_or", "bitwise_xor", "blur", "bnot", "bor", "botk", "botk_ind", "botk_indices", "bxor", "cat", "ceil", "cellular", "cellular_noise", "cielab_to_rgb", "clamp", "cnt", "concat", "concatenate", "conv", "convolution", "corr", "correlation", "cos", "cosh", "cosine_similarity", "cossim", "count", "cov", "crop", "cross", "cubic", "cubic_ease", "cumprod", "cumsum", "dilate", "dist", "distance", "domain_warp", "domain_warp_noise", "dot", "edge", "elastic", "elastic_ease", "entropy", "erf", "erfinv", "erode", "exp", "ezconv", "ezconvolution", "fft", "find", "flatten", "flip", "float", "floor", "flow_ang", "flow_angle", "flow_apply", "flow_mag", "flow_magnitude", "flow_to_image", "fract", "gamma", "gaussian", "gelu", "get_value", "hist", "histogram", "hsv_to_rgb", "ifft", "int", "int_to_rgb", "interpolate_area", "interpolate_linear", "interpolate_nearest", "interpolate_nearest_exact", "join", "length", "lerp", "linspace", "ln", "log", "logspace", "lower", "map", "matmul", "mean", "median", "mode", "moment", "morph_close", "morph_open", "motion_mask", "nan_to_num", "noise", "now", "nvl", "oklab_to_rgb", "overlay", "pad", "percentile", "perlin", "perlin_noise", "perm", "permute", "pinv", "plasma", "plasma_noise", "popcnt", "popcount", "pow", "prcnt", "print", "print_shape", "pshp", "quantile", "quartil", "quartile", "rand", "randb", "randbeta", "randc", "rande", "randg", "randgumbel", "randchi2", "randl", "randln", "randn", "random_bernoulli", "random_beta", "random_cauchy", "random_exponential", "random_gamma", "random_gumbel", "random_chi2", "random_laplace", "random_log_normal", "random_normal", "random_poisson", "random_studentt", "random_uniform", "random_weibull", "randp", "randt", "randu", "randw", "range", "relu", "remap", "replace", "reshape", "rgb_to_cielab", "rgb_to_hsv", "rgb_to_int", "rgb_to_oklab", "ridged", "ridged_noise", "rife", "roll", "round", "rshp", "select", "shape", "shuffle", "sigm", "sign", "sin", "sine", "sine_ease", "sinh", "smax", "smin", "smootherstep", "smoothstep", "snorm", "softmax", "softmin", "softplus", "sort", "split", "sqrt", "stack_clear", "stack_get", "stack_has", "stack_pop", "stack_push", "std", "step", "substr", "substring", "sum", "swap", "tan", "tanh", "tensor", "text_image", "timestamp", "tmax", "tmin", "tnorm", "topk", "topk_ind", "topk_indices", "trim", "turbulence", "unique", "upper", "var", "voronoi", "voronoi_noise", "where", "worley"
]);

export const FUNCTION_META = {
    abs: { minArgs: 1, maxArgs: 1, snippet: "abs()", description: "abs(x) - applies per element absolute value function. Same as |x| for numbers." },
    acos: { minArgs: 1, maxArgs: 1, snippet: "acos()", description: "acos(x) - applies arcus cosinus function to value or each element of value" },
    acosh: { minArgs: 1, maxArgs: 1, snippet: "acosh()", description: "acosh(x) - applies hyperbolic arcus cosinus function to value or each element of value" },
    all: { minArgs: 1, maxArgs: 1, snippet: "all()", description: "all(x) - returns true if all elements of x are non-zero" },
    angle: { minArgs: 1, maxArgs: 1, snippet: "angle()", description: "angle(x) - returns the angle of a complex number or vector" },
    any: { minArgs: 1, maxArgs: 1, snippet: "any()", description: "any(x) - returns true if any element of x is non-zero" },
    append: { minArgs: 2, maxArgs: 2, snippet: "append()", description: "append(x, y) - appends y to the end of x. If inputs are tensors use concatenate(x,...,dim)" },
    argmax: { minArgs: 1, maxArgs: 1, snippet: "argmax()", description: "argmax(x) - returns the index of the maximum value in flattened x" },
    argmin: { minArgs: 1, maxArgs: 1, snippet: "argmin()", description: "argmin(x) - returns the index of the minimum value in flattened x" },
    argsort: { minArgs: 1, maxArgs: 2, snippet: "argsort()", description: "argsort(x, [desc]) - returns the indices that would sort x. defaults to ascending. Uses last dimension to sort" },
    asin: { minArgs: 1, maxArgs: 1, snippet: "asin()", description: "asin(x) - applies arcus sinus function to value or each element of value" },
    asinh: { minArgs: 1, maxArgs: 1, snippet: "asinh()", description: "asinh(x) - applies hyperbolic arcus sinus function to value or each element of value" },
    atan: { minArgs: 1, maxArgs: 1, snippet: "atan()", description: "atan(x) - applies arcus tangents function to value or each element of value" },
    atan2: { minArgs: 2, maxArgs: 2, snippet: "atan2()", description: "atan2(y, x) - computes the arc tangent of y/x, using the signs of both arguments to determine the quadrant" },
    atanh: { minArgs: 1, maxArgs: 1, snippet: "atanh()", description: "atanh(x) - applies hyperbolic arcus tangents function to value or each element of value" },
    band: { minArgs: 2, maxArgs: 2, snippet: "band()", description: "bitwise_and(x, y) - computes the element-wise bitwise AND of x and y" },
    batch_shuffle: { minArgs: 2, maxArgs: 2, snippet: "batch_shuffle()", description: "batch_shuffle(x, indices) - shuffles and duplicates or skips the batch dimension of x according to indices" },
    bitcount: { minArgs: 1, maxArgs: 1, snippet: "bitcount()", description: "bitcount(x) - returns the number of set bits" },
    bitwise_and: { minArgs: 2, maxArgs: 2, snippet: "bitwise_and()", description: "bitwise_and(x, y) - computes the element-wise bitwise AND of x and y" },
    bitwise_not: { minArgs: 1, maxArgs: 1, snippet: "bitwise_not()", description: "bnot(x) - computes the bitwise NOT" },
    bitwise_or: { minArgs: 2, maxArgs: 2, snippet: "bitwise_or()", description: "bitwise_or(x, y) - computes the element-wise bitwise OR of x and y" },
    bitwise_xor: { minArgs: 2, maxArgs: 2, snippet: "bitwise_xor()", description: "bitwise_xor(x, y) - computes the element-wise bitwise XOR of x and y" },
    blur: { minArgs: 2, maxArgs: 3, snippet: "blur()", description: "gaussian(x, sigma, [reshape]) - applies a Gaussian blur to x with specified sigma. if reshape has value of 1.0, then it tries orienting the input such that channel is in the direction of filter. Otherwise it expect color dimension to be the last." },
    bnot: { minArgs: 1, maxArgs: 1, snippet: "bnot()", description: "bnot(x) - computes the bitwise NOT" },
    bor: { minArgs: 2, maxArgs: 2, snippet: "bor()", description: "bitwise_or(x, y) - computes the element-wise bitwise OR of x and y" },
    botk: { minArgs: 2, maxArgs: 2, snippet: "botk()", description: "botk(x, k) - returns the k smallest elements of x.  For tensors it keeps them in place." },
    botk_ind: { minArgs: 2, maxArgs: 2, snippet: "botk_ind()", description: "botk_indices(x, k) - returns the indices of the k smallest elements of x" },
    botk_indices: { minArgs: 2, maxArgs: 2, snippet: "botk_indices()", description: "botk_indices(x, k) - returns the indices of the k smallest elements of x" },
    bxor: { minArgs: 2, maxArgs: 2, snippet: "bxor()", description: "bitwise_xor(x, y) - computes the element-wise bitwise XOR of x and y" },
    cat: { minArgs: 2, maxArgs: null, snippet: "cat()", description: "concatenate(x1, x2, ..., dim) - concatenates tensors along the specified dimension" },
    ceil: { minArgs: 1, maxArgs: 1, snippet: "ceil()", description: "ceil(x) - returns the smallest integer greater than or equal to x" },
    cellular: { minArgs: 2, maxArgs: 5, snippet: "cellular()", description: "cellular_noise(seed, scale, [jitter], [offset], [shape]) - generates Cellular/Voronoi noise" },
    cellular_noise: { minArgs: 2, maxArgs: 5, snippet: "cellular_noise()", description: "cellular_noise(seed, scale, [jitter], [offset], [shape]) - generates Cellular/Voronoi noise" },
    cielab_to_rgb: { minArgs: 1, maxArgs: 3, snippet: "cielab_to_rgb()", description: "cielab_to_rgb(cielab) / cielab_to_rgb(l, a, b) - converts CIELAB to RGB. It has 2 modes. Aither 1 or 3 parameters. With 1 parameter it expects last dimension of 3 and with 3 it concatinates them after converting." },
    clamp: { minArgs: 3, maxArgs: 3, snippet: "clamp()", description: "clamp(x, min, max) - clamps x between min and max per element" },
    cnt: { minArgs: 1, maxArgs: 1, snippet: "cnt()", description: "count(x) - returns the number of elements in x" },
    concat: { minArgs: 2, maxArgs: null, snippet: "concat()", description: "concatenate(x1, x2, ..., dim) - concatenates tensors along the specified dimension" },
    concatenate: { minArgs: 2, maxArgs: null, snippet: "concatenate()", description: "concatenate(x1, x2, ..., dim) - concatenates tensors along the specified dimension" },
    conv: { minArgs: 2, maxArgs: null, snippet: "conv()", description: "convolution(tensor, [kernel_sizes...], kernel) - applies convolution with kernel. Expects [batch,channel, ...]" },
    convolution: { minArgs: 2, maxArgs: null, snippet: "convolution()", description: "convolution(tensor, [kernel_sizes...], kernel) - applies convolution with kernel. Expects [batch,channel, ...]" },
    corr: { minArgs: 2, maxArgs: 2, snippet: "corr()", description: "correlation(x, y) - computes the correlation between x and y" },
    correlation: { minArgs: 2, maxArgs: 2, snippet: "correlation()", description: "correlation(x, y) - computes the correlation between x and y" },
    cos: { minArgs: 1, maxArgs: 1, snippet: "cos()", description: "cos(x) - applies cosinus function to value or each element of value" },
    cosh: { minArgs: 1, maxArgs: 1, snippet: "cosh()", description: "cosh(x) - applies hyperbolic cosinus function to value or each element of value" },
    cosine_similarity: { minArgs: 2, maxArgs: 2, snippet: "cosine_similarity()", description: "cosine_similarity(x, y) - computes the cosine similarity between x and y." },
    cossim: { minArgs: 2, maxArgs: 2, snippet: "cossim()", description: "cosine_similarity(x, y) - computes the cosine similarity between x and y." },
    count: { minArgs: 1, maxArgs: 1, snippet: "count()", description: "count(x) - returns the number of elements in x" },
    cov: { minArgs: 2, maxArgs: 2, snippet: "cov()", description: "cov(x, y) - computes the covariance matrix of x and y" },
    crop: { minArgs: 3, maxArgs: 3, snippet: "crop()", description: "crop(x, start, size) - crops tensor x. Take size and begin at start. start should be the low corner. The result is at most size (if size is bigger then rest of tensor)." },
    cross: { minArgs: 2, maxArgs: 2, snippet: "cross()", description: "cross(x, y) - computes the cross product of x and y. Last dimension must be 3" },
    cubic: { minArgs: 3, maxArgs: 3, snippet: "cubic()", description: "cubic_ease(a, b, t) - cubic ease between a and b" },
    cubic_ease: { minArgs: 3, maxArgs: 3, snippet: "cubic_ease()", description: "cubic_ease(a, b, t) - cubic ease between a and b" },
    cumprod: { minArgs: 1, maxArgs: 1, snippet: "cumprod()", description: "cumprod(x) - computes the cumulative product over first dimension." },
    cumsum: { minArgs: 1, maxArgs: 1, snippet: "cumsum()", description: "cumsum(x) - computes the cumulative sum over first dimension." },
    dilate: { minArgs: 1, maxArgs: 2, snippet: "dilate()", description: "dilate(x, [kernel]) - applies dilation to x. kernel is optional." },
    dist: { minArgs: 4, maxArgs: 4, snippet: "dist()", description: "distance(x1, y1, x2, y2) - computes Euclidean distance between (x1, y1) and (x2, y2)" },
    distance: { minArgs: 4, maxArgs: 4, snippet: "distance()", description: "distance(x1, y1, x2, y2) - computes Euclidean distance between (x1, y1) and (x2, y2)" },
    domain_warp: { minArgs: 4, maxArgs: 8, snippet: "domain_warp()", description: "domain_warp_noise(seed, scale, warp_scale, warp_strength, [octaves], [warp_octaves], [offset], [shape]) - generates domain warped noise" },
    domain_warp_noise: { minArgs: 4, maxArgs: 8, snippet: "domain_warp_noise()", description: "domain_warp_noise(seed, scale, warp_scale, warp_strength, [octaves], [warp_octaves], [offset], [shape]) - generates domain warped noise" },
    dot: { minArgs: 2, maxArgs: 2, snippet: "dot()", description: "dot(x, y) - computes the dot product of x and y. Last dimension must be 3." },
    edge: { minArgs: 1, maxArgs: 2, snippet: "edge()", description: "edge(x, [matrix_size]) - detects edges in x. Matrix size denotes the size of edge detection matrix." },
    elastic: { minArgs: 3, maxArgs: 3, snippet: "elastic()", description: "elastic_ease(a, b, t) - elastic ease between a and b" },
    elastic_ease: { minArgs: 3, maxArgs: 3, snippet: "elastic_ease()", description: "elastic_ease(a, b, t) - elastic ease between a and b" },
    entropy: { minArgs: 1, maxArgs: 1, snippet: "entropy()", description: "entropy(x) - computes shanon entropy" },
    erf: { minArgs: 1, maxArgs: 1, snippet: "erf()", description: "erf(x) - computes the error function -- TODO: MORE DESCRIPTIVE --" },
    erfinv: { minArgs: 1, maxArgs: 1, snippet: "erfinv()", description: "erfinv(x) - computes the inverse error function -- TODO: MORE DESCRIPTIVE --" },
    erode: { minArgs: 1, maxArgs: 2, snippet: "erode()", description: "erode(x, [kernel]) - applies erosion to x. kernel is size of used matrix." },
    exp: { minArgs: 1, maxArgs: 1, snippet: "exp()", description: "exp(x) - applies e^x to value (per element)" },
    ezconv: { minArgs: 2, maxArgs: null, snippet: "ezconv()", description: "ezconvolution(tensor, [kernel_sizes...], kernel) - applies convolution with kernel. Attempts to correctly convolve over size dimensions." },
    ezconvolution: { minArgs: 2, maxArgs: null, snippet: "ezconvolution()", description: "ezconvolution(tensor, [kernel_sizes...], kernel) - applies convolution with kernel. Attempts to correctly convolve over size dimensions." },
    fft: { minArgs: 1, maxArgs: 1, snippet: "fft()", description: "fft(x) - computes  fast Fourier transform of x" },
    find: { minArgs: 2, maxArgs: 2, snippet: "find()", description: "find(s, sub) - returns the index of the first occurrence of sub in s. -1 if not found. Works only for strings." },
    flatten: { minArgs: 1, maxArgs: 1, snippet: "flatten()", description: "flatten(x) - flattens tensor into a 1D tensor" },
    flip: { minArgs: 2, maxArgs: 2, snippet: "flip()", description: "flip(x, dims) - reverses the order of elements along the specified dimensions. Works also for text and list with dims=0" },
    float: { minArgs: 1, maxArgs: 1, snippet: "float()", description: "float(x) - casts x to float" },
    floor: { minArgs: 1, maxArgs: 1, snippet: "floor()", description: "floor(x) - returns the largest integer less than or equal to x" },
    flow_ang: { minArgs: 1, maxArgs: 1, snippet: "flow_ang()", description: "flow_angle(x) - computes the angle of optical flow (basically angle() but real and imaginery is separate in 2 dimensions)" },
    flow_angle: { minArgs: 1, maxArgs: 1, snippet: "flow_angle()", description: "flow_angle(x) - computes the angle of optical flow (basically angle() but real and imaginery is separate in 2 dimensions)" },
    flow_apply: { minArgs: 2, maxArgs: 2, snippet: "flow_apply()", description: "flow_apply(image, flow) - applies optical flow to an image" },
    flow_mag: { minArgs: 1, maxArgs: 1, snippet: "flow_mag()", description: "flow_magnitude(x) - computes the magnitude of optical flow (or any other structure with last dimension of 2)" },
    flow_magnitude: { minArgs: 1, maxArgs: 1, snippet: "flow_magnitude()", description: "flow_magnitude(x) - computes the magnitude of optical flow (or any other structure with last dimension of 2)" },
    flow_to_image: { minArgs: 1, maxArgs: 1, snippet: "flow_to_image()", description: "flow_to_image(x) - converts optical flow x to an RGB image. Up-Down is <COLOR1> Left-right <COLOR2>" },
    fract: { minArgs: 1, maxArgs: 1, snippet: "fract()", description: "fract(x) - returns the fractional part of x: x - floor(x)" },
    gamma: { minArgs: 1, maxArgs: 1, snippet: "gamma()", description: "gamma(x) - computes the gamma function (per element)" },
    gaussian: { minArgs: 2, maxArgs: 3, snippet: "gaussian()", description: "gaussian(x, sigma, [reshape]) - applies a Gaussian blur to x with specified sigma. if reshape has value of 1.0, then it tries orienting the input such that channel is in the direction of filter. Otherwise it expect color dimension to be the last." },
    gelu: { minArgs: 1, maxArgs: 1, snippet: "gelu()", description: "gelu(x) - applies the Gaussian Error Linear Unit (GELU) activation function" },
    get_value: { minArgs: 2, maxArgs: 2, snippet: "get_value()", description: "get_value(slot) - returns the value at slot from stack" },
    hist: { minArgs: 4, maxArgs: 4, snippet: "hist()", description: "histogram(x, bins, min, max) - computes histogram" },
    histogram: { minArgs: 4, maxArgs: 4, snippet: "histogram()", description: "histogram(x, bins, min, max) - computes histogram" },
    hsv_to_rgb: { minArgs: 1, maxArgs: 4, snippet: "hsv_to_rgb()", description: "hsv_to_rgb(hsv, [degrees]) / hsv_to_rgb(h, s, v, [degrees]) - converts HSV to RGB. It has 2 modes. Aither 1 or 3 parameters. With 1 parameter it expects last dimension of 3 and with 3 it concatinates them after converting." },
    ifft: { minArgs: 1, maxArgs: 2, snippet: "ifft()", description: "ifft(x, [axis]) - inverse fast Fourier transform" },
    int: { minArgs: 1, maxArgs: 1, snippet: "int()", description: "int(x) - casts x to integer" },
    int_to_rgb: { minArgs: 1, maxArgs: 1, snippet: "int_to_rgb()", description: "int_to_rgb(val) - converts an integer to an RGB color. If input is tensor it stacks the resulting R, G and B tensors using last dimension. If It is list, List of lists is returned and if value, 3 long list is returned." },
    interpolate_area: { minArgs: 2, maxArgs: 2, snippet: "interpolate_area()", description: "interpolate_area(x, y) - performs area interpolation X. Assumes that dim 0 is batch and dim 1 = channel" },
    interpolate_linear: { minArgs: 2, maxArgs: 2, snippet: "interpolate_linear()", description: "interpolate_linear(x, y) - performs linear interpolation on X. Assumes that dim 0 is batch and dim 1 = channel" },
    interpolate_nearest: { minArgs: 2, maxArgs: 2, snippet: "interpolate_nearest()", description: "interpolate_nearest_exact(x, y) - performs nearest neighbor interpolation X. Assumes that dim 0 is batch and dim 1 = channel" },
    interpolate_nearest_exact: { minArgs: 2, maxArgs: 2, snippet: "interpolate_nearest_exact()", description: "interpolate_nearest_exact(x, y) - performs nearest neighbor interpolation X. Assumes that dim 0 is batch and dim 1 = channel" },
    join: { minArgs: 1, maxArgs: 2, snippet: "join()", description: "join(x, [separator]) - joins strings in list using separator. Defalut separator is \"\". If you want to join tensors use concatinate(...)" },
    length: { minArgs: 1, maxArgs: 1, snippet: "length()", description: "count(x) - returns the number of elements in x" },
    lerp: { minArgs: 3, maxArgs: 3, snippet: "lerp()", description: "lerp(a, b, t) - linear interpolation between a and b by t per element. t can be float or tensor." },
    linspace: { minArgs: 3, maxArgs: 3, snippet: "linspace()", description: "linspace(start, stop, num) - creates num linearly spaced values from start to stop (inclusive). Use range if you want to control the step between values." },
    ln: { minArgs: 1, maxArgs: 1, snippet: "ln()", description: "ln(x) - applies natural logarithm to value (per element). Negative numbers return NaN (not a number)" },
    log: { minArgs: 1, maxArgs: 1, snippet: "log()", description: "log(x) - applies base 10 logarithm to value (per element). Negative numbers return NaN (not a number)" },
    logspace: { minArgs: 4, maxArgs: 4, snippet: "logspace()", description: "logspace(start, stop, num, base) - creates logarithmically spaced values" },
    lower: { minArgs: 1, maxArgs: 1, snippet: "lower()", description: "lower(x) - converts string to lowercase" },
    map: { minArgs: 2, maxArgs: null, snippet: "map()", description: "map(tensor, coord1, [coord2], [coord3]) - samples/remaps input tensor using coordinates" },
    matmul: { minArgs: 2, maxArgs: 2, snippet: "matmul()", description: "matmul(x, y) - computes the matrix multiplication of x and y" },
    mean: { minArgs: 1, maxArgs: 1, snippet: "mean()", description: "mean(x) - computes the arithmetic mean of elements of x" },
    median: { minArgs: 1, maxArgs: 1, snippet: "median()", description: "median(x) - computes the median of elements of x" },
    mode: { minArgs: 1, maxArgs: 1, snippet: "mode()", description: "mode(x) - computes the mode of elements of x" },
    moment: { minArgs: 3, maxArgs: 3, snippet: "moment()", description: "moment(x, a, k) - computes the k-th moment of x around a" },
    morph_close: { minArgs: 1, maxArgs: 2, snippet: "morph_close()", description: "morph_close(x, [kernel]) - applies morphological closing to x. kernel is size of used matrix." },
    morph_open: { minArgs: 1, maxArgs: 2, snippet: "morph_open()", description: "morph_open(x, [kernel]) - applies morphological opening to x. kernel is size of used matrix." },
    motion_mask: { minArgs: 1, maxArgs: 1, snippet: "motion_mask()", description: "motion_mask(x) - generates a motion mask from optical flow" },
    nan_to_num: { minArgs: 4, maxArgs: 4, snippet: "nan_to_num()", description: "nan_to_num(x, nan, pos_inf, neg_inf) - null value replacement - inspired by NVL" },
    noise: { minArgs: 1, maxArgs: 2, snippet: "noise()", description: "random_normal(seed, [shape]) - generates normally distributed random noise" },
    now: { minArgs: 0, maxArgs: 0, snippet: "now()", description: "timestamp() - returns the current system timestamp" },
    nvl: { minArgs: 4, maxArgs: 4, snippet: "nvl()", description: "nan_to_num(x, nan, pos_inf, neg_inf) - null value replacement - inspired by NVL" },
    oklab_to_rgb: { minArgs: 1, maxArgs: 3, snippet: "oklab_to_rgb()", description: "oklab_to_rgb(oklab) / oklab_to_rgb(l, a, b) - converts OKLab to RGB. It has 2 modes. Aither 1 or 3 parameters. With 1 parameter it expects last dimension of 3 and with 3 it concatinates them after converting." },
    overlay: { minArgs: 3, maxArgs: 4, snippet: "overlay()", description: "overlay(base, overlay, offset, [opacity]) - overlays overlay on base at offset. Opacity controls blending. It can be tensor or float. If it is tensor it should be the same shape as overlay." },
    pad: { minArgs: 2, maxArgs: 2, snippet: "pad()", description: "pad(x, padding) - pads tensor x with specified padding (dim 0 neg, dim 0 pos, dim 1 ...)" },
    percentile: { minArgs: 2, maxArgs: 2, snippet: "percentile()", description: "percentile(x, p) - computes the p-th percentile of x" },
    perlin: { minArgs: 2, maxArgs: 5, snippet: "perlin()", description: "perlin_noise(seed, scale, [octaves], [offset], [shape]) - generates Perlin noise" },
    perlin_noise: { minArgs: 2, maxArgs: 5, snippet: "perlin_noise()", description: "perlin_noise(seed, scale, [octaves], [offset], [shape]) - generates Perlin noise" },
    perm: { minArgs: 2, maxArgs: 2, snippet: "perm()", description: "permute(x, dims) - permutes the dimensions of tensor x according to dims" },
    permute: { minArgs: 2, maxArgs: 2, snippet: "permute()", description: "permute(x, dims) - permutes the dimensions of tensor x according to dims" },
    pinv: { minArgs: 1, maxArgs: 1, snippet: "pinv()", description: "pinv(x) - computes the permutative inverse of a list x (list must have uniqe elements) -- TODO: CHECK --" },
    plasma: { minArgs: 2, maxArgs: 5, snippet: "plasma()", description: "plasma_noise(seed, scale, [octaves], [offset], [shape]) - generates Plasma/Turbulence noise - same as perlin but default octaves 4" },
    plasma_noise: { minArgs: 2, maxArgs: 5, snippet: "plasma_noise()", description: "plasma_noise(seed, scale, [octaves], [offset], [shape]) - generates Plasma/Turbulence noise - same as perlin but default octaves 4" },
    popcnt: { minArgs: 1, maxArgs: 1, snippet: "popcnt()", description: "bitcount(x) - returns the number of set bits" },
    popcount: { minArgs: 1, maxArgs: 1, snippet: "popcount()", description: "bitcount(x) - returns the number of set bits" },
    pow: { minArgs: 2, maxArgs: 2, snippet: "pow()", description: "pow(x, y) - computes x raised to the power of y" },
    prcnt: { minArgs: 2, maxArgs: 2, snippet: "prcnt()", description: "percentile(x, p) - computes the p-th percentile of x" },
    print: { minArgs: 1, maxArgs: 1, snippet: "print()", description: "print(x) - prints the value of x to the console while passing output unchanged" },
    print_shape: { minArgs: 1, maxArgs: 1, snippet: "print_shape()", description: "print_shape(x) - prints the shape of the tensor x" },
    pshp: { minArgs: 1, maxArgs: 1, snippet: "pshp()", description: "print_shape(x) - prints the shape of the tensor x" },
    quantile: { minArgs: 2, maxArgs: 2, snippet: "quantile()", description: "quantile(x, q) - computes the q-th quantile of x" },
    quartil: { minArgs: 2, maxArgs: 2, snippet: "quartil()", description: "quartile(x, q) - computes the q-th quartile of x" },
    quartile: { minArgs: 2, maxArgs: 2, snippet: "quartile()", description: "quartile(x, q) - computes the q-th quartile of x" },
    rand: { minArgs: 1, maxArgs: 2, snippet: "rand()", description: "random_uniform(seed, [shape]) - generates uniformly distributed random noise" },
    randb: { minArgs: 2, maxArgs: 3, snippet: "randb()", description: "random_bernoulli(seed, probability, [shape]) - generates Bernoulli distributed random values (0 or 1). Probability can be a tensor" },
    randbeta: { minArgs: 3, maxArgs: 4, snippet: "randbeta()", description: "random_beta(seed, alpha, beta, [shape]) - generates Beta distributed random values" },
    randc: { minArgs: 3, maxArgs: 4, snippet: "randc()", description: "random_cauchy(seed, median, sigma, [shape]) - generates Cauchy distributed random values." },
    rande: { minArgs: 2, maxArgs: 3, snippet: "rande()", description: "random_exponential(seed, lambda, [shape]) - generates exponentially distributed random values" },
    randg: { minArgs: 3, maxArgs: 4, snippet: "randg()", description: "random_gamma(seed, shape_param, scale, [shape]) - generates Gamma distributed random values." },
    randgumbel: { minArgs: 3, maxArgs: 4, snippet: "randgumbel()", description: "random_gumbel(seed, loc, scale, [shape]) - generates Gumbel distributed random values" },
    randchi2: { minArgs: 2, maxArgs: 3, snippet: "randchi2()", description: "random_chi2(seed, df, [shape]) - generates Chi-squared distributed random values" },
    randl: { minArgs: 3, maxArgs: 4, snippet: "randl()", description: "random_laplace(seed, loc, scale, [shape]) - generates Laplace distributed random values" },
    randln: { minArgs: 3, maxArgs: 4, snippet: "randln()", description: "random_log_normal(seed, mean, std, [shape]) - generates log-normally distributed random values." },
    randn: { minArgs: 1, maxArgs: 2, snippet: "randn()", description: "random_normal(seed, [shape]) - generates normally distributed random noise" },
    random_bernoulli: { minArgs: 2, maxArgs: 3, snippet: "random_bernoulli()", description: "random_bernoulli(seed, probability, [shape]) - generates Bernoulli distributed random values (0 or 1). Probability can be a tensor" },
    random_beta: { minArgs: 3, maxArgs: 4, snippet: "random_beta()", description: "random_beta(seed, alpha, beta, [shape]) - generates Beta distributed random values" },
    random_cauchy: { minArgs: 3, maxArgs: 4, snippet: "random_cauchy()", description: "random_cauchy(seed, median, sigma, [shape]) - generates Cauchy distributed random values." },
    random_exponential: { minArgs: 2, maxArgs: 3, snippet: "random_exponential()", description: "random_exponential(seed, lambda, [shape]) - generates exponentially distributed random values" },
    random_gamma: { minArgs: 3, maxArgs: 4, snippet: "random_gamma()", description: "random_gamma(seed, shape_param, scale, [shape]) - generates Gamma distributed random values." },
    random_gumbel: { minArgs: 3, maxArgs: 4, snippet: "random_gumbel()", description: "random_gumbel(seed, loc, scale, [shape]) - generates Gumbel distributed random values" },
    random_chi2: { minArgs: 2, maxArgs: 3, snippet: "random_chi2()", description: "random_chi2(seed, df, [shape]) - generates Chi-squared distributed random values" },
    random_laplace: { minArgs: 3, maxArgs: 4, snippet: "random_laplace()", description: "random_laplace(seed, loc, scale, [shape]) - generates Laplace distributed random values" },
    random_log_normal: { minArgs: 3, maxArgs: 4, snippet: "random_log_normal()", description: "random_log_normal(seed, mean, std, [shape]) - generates log-normally distributed random values." },
    random_normal: { minArgs: 1, maxArgs: 2, snippet: "random_normal()", description: "random_normal(seed, [shape]) - generates normally distributed random noise" },
    random_poisson: { minArgs: 2, maxArgs: 3, snippet: "random_poisson()", description: "random_poisson(seed, lambda, [shape]) - generates Poisson distributed random values." },
    random_studentt: { minArgs: 2, maxArgs: 3, snippet: "random_studentt()", description: "random_studentt(seed, df, [shape]) - generates Student-t distributed random values" },
    random_uniform: { minArgs: 1, maxArgs: 2, snippet: "random_uniform()", description: "random_uniform(seed, [shape]) - generates uniformly distributed random noise" },
    random_weibull: { minArgs: 3, maxArgs: 4, snippet: "random_weibull()", description: "random_weibull(seed, scale, concentration, [shape]) - generates Weibull distributed random values" },
    randp: { minArgs: 2, maxArgs: 3, snippet: "randp()", description: "random_poisson(seed, lambda, [shape]) - generates Poisson distributed random values." },
    randt: { minArgs: 2, maxArgs: 3, snippet: "randt()", description: "random_studentt(seed, df, [shape]) - generates Student-t distributed random values" },
    randu: { minArgs: 1, maxArgs: 2, snippet: "randu()", description: "random_uniform(seed, [shape]) - generates uniformly distributed random noise" },
    randw: { minArgs: 3, maxArgs: 4, snippet: "randw()", description: "random_weibull(seed, scale, concentration, [shape]) - generates Weibull distributed random values" },
    range: { minArgs: 3, maxArgs: 3, snippet: "range()", description: "range(start, stop, step) - creates a range of values between start (inclusive) and stop (exclusive) using step. Use linspace if you want value count." },
    relu: { minArgs: 1, maxArgs: 1, snippet: "relu()", description: "relu(x) - applies rectified linear unit function: max(0, x)" },
    remap: { minArgs: 5, maxArgs: 5, snippet: "remap()", description: "remap(v, i_min, i_max, o_min, o_max) - remaps values from input range to output range" },
    replace: { minArgs: 3, maxArgs: 3, snippet: "replace()", description: "replace(s, old, new) - replaces occurrences of old with new in s. Mostly for strings but can work with lists and tensors." },
    reshape: { minArgs: 2, maxArgs: 2, snippet: "reshape()", description: "reshape(x, shape) - reshapes tensor x to the specified shape" },
    rgb_to_cielab: { minArgs: 1, maxArgs: 3, snippet: "rgb_to_cielab()", description: "rgb_to_cielab(r, [g], [b]) - converts RGB to CIELAB. It has 2 modes. Aither 1 or 3 parameters. With 1 parameter it expects last dimension of 3 and with 3 it concatinates them after converting." },
    rgb_to_hsv: { minArgs: 1, maxArgs: 4, snippet: "rgb_to_hsv()", description: "rgb_to_hsv(rgb, [degrees]) / rgb_to_hsv(r, g, b, [degrees]) - converts RGB to HSV. It has 2 modes. Aither 1 or 3 parameters. With 1 parameter it expects last dimension of 3 and with 3 it concatinates them after converting. If degrees is specified and nonzero it returns hue as 0-360 instead of 0-1" },
    rgb_to_int: { minArgs: 1, maxArgs: 3, snippet: "rgb_to_int()", description: "rgb_to_int(r, [g, b]) - converts RGB components to an integer It uses last dimension of tensor (or list) as R,G,B if one value. Othervise uses whole thing as channel." },
    rgb_to_oklab: { minArgs: 1, maxArgs: 3, snippet: "rgb_to_oklab()", description: "rgb_to_oklab(r, [g], [b]) - converts RGB to OKLab. It has 2 modes. Aither 1 or 3 parameters. With 1 parameter it expects last dimension of 3 and with 3 it concatinates them after converting." },
    ridged: { minArgs: 2, maxArgs: 5, snippet: "ridged()", description: "ridged_noise(seed, scale, [octaves], [offset], [shape]) - generates ridged multi-fractal noise" },
    ridged_noise: { minArgs: 2, maxArgs: 5, snippet: "ridged_noise()", description: "ridged_noise(seed, scale, [octaves], [offset], [shape]) - generates ridged multi-fractal noise" },
    rife: { minArgs: 4, maxArgs: 5, snippet: "rife()", description: "rife(image1, image2, [tile_size], [iterations], [multi_scale]) - computes an intermediate frame between image1 and image2 using RIFE - tile_size: chuncks image to overlapping tile_size*tile_size parts to conserve memory Default is 1024x1024 when over 2MPx. When tiling size is between 0 - 1 it takes as a fraction of the resolution - iterations: how many times to run RIFE model. Default 12 - multi_scale: also use low resolution of base image for giant movements" },
    roll: { minArgs: 2, maxArgs: 3, snippet: "roll()", description: "roll(x, shifts, [axis]) - rolls tensor x along axis" },
    round: { minArgs: 1, maxArgs: 1, snippet: "round()", description: "round(x) - rounds x to the nearest integer" },
    rshp: { minArgs: 2, maxArgs: 2, snippet: "rshp()", description: "reshape(x, shape) - reshapes tensor x to the specified shape" },
    select: { minArgs: 2, maxArgs: 2, snippet: "select()", description: "batch_shuffle(x, indices) - shuffles and duplicates or skips the batch dimension of x according to indices" },
    shape: { minArgs: 1, maxArgs: 1, snippet: "shape()", description: "shape(x) - returns the shape of tensor as a list" },
    shuffle: { minArgs: 2, maxArgs: 2, snippet: "shuffle()", description: "batch_shuffle(x, indices) - shuffles and duplicates or skips the batch dimension of x according to indices" },
    sigm: { minArgs: 1, maxArgs: 1, snippet: "sigm()", description: "sigm(x) - applies the sigmoid function: 1 / (1 + exp(-x))" },
    sign: { minArgs: 1, maxArgs: 1, snippet: "sign()", description: "sign(x) - returns the sign of x: -1, 0, or 1" },
    sin: { minArgs: 1, maxArgs: 1, snippet: "sin()", description: "sin(x) - applies sinus function to value or each element of value" },
    sine: { minArgs: 3, maxArgs: 3, snippet: "sine()", description: "sine_ease(a, b, t) - sine easing between a and b" },
    sine_ease: { minArgs: 3, maxArgs: 3, snippet: "sine_ease()", description: "sine_ease(a, b, t) - sine easing between a and b" },
    sinh: { minArgs: 1, maxArgs: 1, snippet: "sinh()", description: "sinh(x) - applies hyperbolic sinus function to value or each element of value" },
    smax: { minArgs: 1, maxArgs: null, snippet: "smax()", description: "smax(x, ...) - computes the maximum of inputs or elements. Tensors must have the same size or be broadcastable to same size." },
    smin: { minArgs: 1, maxArgs: null, snippet: "smin()", description: "smin(x, ...) - computes the minimum of inputs or elements. Tensors must have the same size or be broadcastable to same size." },
    smootherstep: { minArgs: 3, maxArgs: 3, snippet: "smootherstep()", description: "smootherstep(x, edge0, edge1) - smoother interpolation between edge0 and edge1" },
    smoothstep: { minArgs: 3, maxArgs: 3, snippet: "smoothstep()", description: "smoothstep(x, edge0, edge1) - smooth interpolation between edge0 and edge1" },
    snorm: { minArgs: 1, maxArgs: 2, snippet: "snorm()", description: "snorm(x,[dim]) - frobenius norm of tensor. Along dimension if dimension specified. Dimension can be a list. Defaults to no dimension." },
    softmax: { minArgs: 1, maxArgs: 2, snippet: "softmax()", description: "softmax(x, [axis]) - applies the softmax function to x (sum of slice == 1.0 and max value <= 1.0). axis defaults to last." },
    softmin: { minArgs: 1, maxArgs: 2, snippet: "softmin()", description: "softmin(x, [axis]) - applies the softmin function to x (same as softmax(-x,[axis])). axis defaults to last." },
    softplus: { minArgs: 1, maxArgs: 1, snippet: "softplus()", description: "softplus(x) - applies the softplus function: ln(1 + exp(x))" },
    sort: { minArgs: 1, maxArgs: 1, snippet: "sort()", description: "sort(x) - returns a sorted version of x (If input is tensor, it sorts the last dimension)" },
    split: { minArgs: 1, maxArgs: 2, snippet: "split()", description: "split(x, [delimiter]) - splits string to list of strings based on delimiter. Default is space." },
    sqrt: { minArgs: 1, maxArgs: 1, snippet: "sqrt()", description: "sqrt(x) - applies sqere root per element. Negative numbers return NaN (not a number)" },
    stack_clear: { minArgs: 1, maxArgs: 1, snippet: "stack_clear()", description: "stack_clear(slot) - clears the contents of slot stack" },
    stack_get: { minArgs: 1, maxArgs: 1, snippet: "stack_get()", description: "stack_get(slot) - returns the last pushed value in slot without popping it" },
    stack_has: { minArgs: 1, maxArgs: 1, snippet: "stack_has()", description: "stack_has(slot) - returns 1.0 if slot exists in state storage and is not empty else returns 0.0" },
    stack_pop: { minArgs: 1, maxArgs: 1, snippet: "stack_pop()", description: "stack_pop(slot) - removes and returns the last element of slot stack" },
    stack_push: { minArgs: 2, maxArgs: 2, snippet: "stack_push()", description: "stack_push(slot, val) - pushes val onto the end of slot stack" },
    std: { minArgs: 1, maxArgs: 1, snippet: "std()", description: "std(x) - computes the standard deviation of elements of x" },
    step: { minArgs: 2, maxArgs: 2, snippet: "step()", description: "step(x, edge) - returns 0 if x < edge, else 1" },
    substr: { minArgs: 2, maxArgs: 3, snippet: "substr()", description: "substring(s, start, [end]) - returns a substring of s from start to end. If end is not supplied, it uses end of string" },
    substring: { minArgs: 2, maxArgs: 3, snippet: "substring()", description: "substring(s, start, [end]) - returns a substring of s from start to end. If end is not supplied, it uses end of string" },
    sum: { minArgs: 1, maxArgs: 1, snippet: "sum()", description: "sum(x) - computes the sum of elements of x" },
    swap: { minArgs: 4, maxArgs: 4, snippet: "swap()", description: "swap(x, dim, idx1, idx2) - swaps elements along dim between idx1 and idx2" },
    tan: { minArgs: 1, maxArgs: 1, snippet: "tan()", description: "tan(x) - applies tangents function to value or each element of value" },
    tanh: { minArgs: 1, maxArgs: 1, snippet: "tanh()", description: "tanh(x) - applies hyperbolic tangents function to value or each element of value" },
    tensor: { minArgs: 2, maxArgs: 3, snippet: "tensor()", description: "tensor(shape, [value], [dtype_template]) - creates a tensor with specified shape and optional value/type. Default value is 0 and default format FP32" },
    text_image: { minArgs: 3, maxArgs: 9, snippet: "text_image()", description: "text_image(text, font, size, [max_width], [weight], [rotation_angle], [line_spacing], [italic], [underline]) - renders text to an 2D tensor" },
    timestamp: { minArgs: 0, maxArgs: 0, snippet: "timestamp()", description: "timestamp() - returns the current system timestamp" },
    tmax: { minArgs: 2, maxArgs: 2, snippet: "tmax()", description: "tmax(x,y) - elementwise maximum of tensor or list. max(x,y) when inputs are floats" },
    tmin: { minArgs: 2, maxArgs: 2, snippet: "tmin()", description: "tmin(x, y) - elementwise minimum of tensor or list. min(x,y) when inputs are floats" },
    tnorm: { minArgs: 1, maxArgs: 1, snippet: "tnorm()", description: "tnorm(x) - normalises tensor or list by multiplication such that sum(x^2)==1.0 for each slice. The slice is last dimension of the tensor." },
    topk: { minArgs: 2, maxArgs: 2, snippet: "topk()", description: "topk(x, k) - returns the k largest elements of x. For tensors it keeps them in place." },
    topk_ind: { minArgs: 2, maxArgs: 2, snippet: "topk_ind()", description: "topk_indices(x, k) - returns the indices of the k largest elements of x" },
    topk_indices: { minArgs: 2, maxArgs: 2, snippet: "topk_indices()", description: "topk_indices(x, k) - returns the indices of the k largest elements of x" },
    trim: { minArgs: 1, maxArgs: 1, snippet: "trim()", description: "trim(x) - removes leading and trailing whitespace from string" },
    turbulence: { minArgs: 2, maxArgs: 5, snippet: "turbulence()", description: "plasma_noise(seed, scale, [octaves], [offset], [shape]) - generates Plasma/Turbulence noise - same as perlin but default octaves 4" },
    unique: { minArgs: 1, maxArgs: 1, snippet: "unique()", description: "unique(x) - returns the unique elements (sorted,) --TODO: FINISH --" },
    upper: { minArgs: 1, maxArgs: 1, snippet: "upper()", description: "upper(x) - converts string to uppercase" },
    var: { minArgs: 1, maxArgs: 1, snippet: "var()", description: "var(x) - computes the variance of elements of x" },
    voronoi: { minArgs: 2, maxArgs: 5, snippet: "voronoi()", description: "cellular_noise(seed, scale, [jitter], [offset], [shape]) - generates Cellular/Voronoi noise" },
    voronoi_noise: { minArgs: 2, maxArgs: 5, snippet: "voronoi_noise()", description: "cellular_noise(seed, scale, [jitter], [offset], [shape]) - generates Cellular/Voronoi noise" },
    where: { minArgs: 3, maxArgs: 3, snippet: "where()", description: "where(condition, x, y) - returns x if condition is true, else y. Runs per element." },
    worley: { minArgs: 2, maxArgs: 5, snippet: "worley()", description: "cellular_noise(seed, scale, [jitter], [offset], [shape]) - generates Cellular/Voronoi noise" },
};