// Generated automatically by compile.ps1. Do not edit.

export const KEYWORDS = new Set([
"break", "continue", "else", "for", "if", "in", "none", "null", "return", "while"
]);

export const CONSTANTS = new Set([
"e", "pi"
]);

export const FUNCTIONS = new Set([
"abs", "acos", "acosh", "all", "angle", "any", "append", "argmax", "argmin", "argsort", "asin", "asinh", "atan", "atan2", "atanh", "band", "batch_shuffle", "bitcount", "bitwise_and", "bitwise_not", "bitwise_or", "bitwise_xor", "blur", "bnot", "bor", "botk", "botk_ind", "botk_indices", "bxor", "cat", "ceil", "cellular", "cellular_noise", "cielab_to_rgb", "clamp", "cnt", "concat", "concatenate", "conv", "convolution", "corr", "correlation", "cos", "cosh", "cosine_similarity", "cossim", "count", "cov", "crop", "cross", "cubic", "cubic_ease", "cumprod", "cumsum", "dilate", "dist", "distance", "domain_warp", "domain_warp_noise", "dot", "edge", "elastic", "elastic_ease", "entropy", "erf", "erfinv", "erode", "exp", "ezconv", "ezconvolution", "fft", "find", "flatten", "flip", "float", "floor", "flow_ang", "flow_angle", "flow_apply", "flow_mag", "flow_magnitude", "flow_to_image", "fract", "gamma", "gaussian", "gelu", "get_value", "hist", "histogram", "hsv_to_rgb", "ifft", "int", "int_to_rgb", "interpolate_area", "interpolate_linear", "interpolate_nearest", "interpolate_nearest_exact", "join", "length", "lerp", "linspace", "ln", "log", "logspace", "lower", "map", "matmul", "mean", "median", "mode", "moment", "morph_close", "morph_open", "motion_mask", "nan_to_num", "noise", "now", "nvl", "oklab_to_rgb", "overlay", "pad", "percentile", "perlin", "perlin_noise", "perm", "permute", "pinv", "plasma", "plasma_noise", "popcnt", "popcount", "pow", "prcnt", "print", "print_shape", "pshp", "quantile", "quartil", "quartile", "rand", "randb", "randbeta", "randc", "rande", "randg", "randgumbel", "randchi2", "randl", "randln", "randn", "random_bernoulli", "random_beta", "random_cauchy", "random_exponential", "random_gamma", "random_gumbel", "random_chi2", "random_laplace", "random_log_normal", "random_normal", "random_poisson", "random_studentt", "random_uniform", "random_weibull", "randp", "randt", "randu", "randw", "range", "relu", "remap", "replace", "reshape", "rgb_to_cielab", "rgb_to_hsv", "rgb_to_int", "rgb_to_oklab", "ridged", "ridged_noise", "rife", "roll", "round", "rshp", "select", "shape", "shuffle", "sigm", "sign", "sin", "sine", "sine_ease", "sinh", "smax", "smin", "smootherstep", "smoothstep", "snorm", "softmax", "softmin", "softplus", "sort", "split", "sqrt", "stack_clear", "stack_get", "stack_has", "stack_pop", "stack_push", "std", "step", "substr", "substring", "sum", "swap", "tan", "tanh", "tensor", "text_image", "timestamp", "tmax", "tmin", "tnorm", "topk", "topk_ind", "topk_indices", "trim", "turbulence", "unique", "upper", "var", "voronoi", "voronoi_noise", "where", "worley"
]);

export const FUNCTION_META = {
    abs: { minArgs: 1, maxArgs: 1, snippet: "abs()", description: "abs(x) - applies per element absolute value function. Same as |x| for numbers." },
    acos: { minArgs: 1, maxArgs: 1, snippet: "acos()", description: "acos(x) - applies arcus cosinus function to value or each element of value" },
    acosh: { minArgs: 1, maxArgs: 1, snippet: "acosh()", description: "acosh(x) - applies hyperbolic arcus cosinus function to value or each element of value" },
    all: { minArgs: 1, maxArgs: 1, snippet: "all()", description: "" },
    angle: { minArgs: 1, maxArgs: 1, snippet: "angle()", description: "" },
    any: { minArgs: 1, maxArgs: 1, snippet: "any()", description: "" },
    append: { minArgs: 2, maxArgs: 2, snippet: "append()", description: "" },
    argmax: { minArgs: 1, maxArgs: 1, snippet: "argmax()", description: "" },
    argmin: { minArgs: 1, maxArgs: 1, snippet: "argmin()", description: "" },
    argsort: { minArgs: 1, maxArgs: 2, snippet: "argsort()", description: "" },
    asin: { minArgs: 1, maxArgs: 1, snippet: "asin()", description: "asin(x) - applies arcus sinus function to value or each element of value" },
    asinh: { minArgs: 1, maxArgs: 1, snippet: "asinh()", description: "asinh(x) - applies hyperbolic arcus sinus function to value or each element of value" },
    atan: { minArgs: 1, maxArgs: 1, snippet: "atan()", description: "atan(x) - applies arcus tangents function to value or each element of value" },
    atan2: { minArgs: 2, maxArgs: 2, snippet: "atan2()", description: "" },
    atanh: { minArgs: 1, maxArgs: 1, snippet: "atanh()", description: "atanh(x) - applies hyperbolic arcus tangents function to value or each element of value" },
    band: { minArgs: 2, maxArgs: 2, snippet: "band()", description: "" },
    batch_shuffle: { minArgs: 2, maxArgs: 2, snippet: "batch_shuffle()", description: "" },
    bitcount: { minArgs: 1, maxArgs: 1, snippet: "bitcount()", description: "" },
    bitwise_and: { minArgs: 2, maxArgs: 2, snippet: "bitwise_and()", description: "" },
    bitwise_not: { minArgs: 1, maxArgs: 1, snippet: "bitwise_not()", description: "" },
    bitwise_or: { minArgs: 2, maxArgs: 2, snippet: "bitwise_or()", description: "" },
    bitwise_xor: { minArgs: 2, maxArgs: 2, snippet: "bitwise_xor()", description: "" },
    blur: { minArgs: 2, maxArgs: 3, snippet: "blur()", description: "" },
    bnot: { minArgs: 1, maxArgs: 1, snippet: "bnot()", description: "" },
    bor: { minArgs: 2, maxArgs: 2, snippet: "bor()", description: "" },
    botk: { minArgs: 2, maxArgs: 2, snippet: "botk()", description: "" },
    botk_ind: { minArgs: 2, maxArgs: 2, snippet: "botk_ind()", description: "" },
    botk_indices: { minArgs: 2, maxArgs: 2, snippet: "botk_indices()", description: "" },
    bxor: { minArgs: 2, maxArgs: 2, snippet: "bxor()", description: "" },
    cat: { minArgs: 2, maxArgs: null, snippet: "cat()", description: "" },
    ceil: { minArgs: 1, maxArgs: 1, snippet: "ceil()", description: "" },
    cellular: { minArgs: 2, maxArgs: 5, snippet: "cellular()", description: "" },
    cellular_noise: { minArgs: 2, maxArgs: 5, snippet: "cellular_noise()", description: "" },
    cielab_to_rgb: { minArgs: 1, maxArgs: 3, snippet: "cielab_to_rgb()", description: "" },
    clamp: { minArgs: 3, maxArgs: 3, snippet: "clamp()", description: "" },
    cnt: { minArgs: 1, maxArgs: 1, snippet: "cnt()", description: "" },
    concat: { minArgs: 2, maxArgs: null, snippet: "concat()", description: "" },
    concatenate: { minArgs: 2, maxArgs: null, snippet: "concatenate()", description: "" },
    conv: { minArgs: 2, maxArgs: null, snippet: "conv()", description: "" },
    convolution: { minArgs: 2, maxArgs: null, snippet: "convolution()", description: "" },
    corr: { minArgs: 2, maxArgs: 2, snippet: "corr()", description: "" },
    correlation: { minArgs: 2, maxArgs: 2, snippet: "correlation()", description: "" },
    cos: { minArgs: 1, maxArgs: 1, snippet: "cos()", description: "cos(x) - applies cosinus function to value or each element of value" },
    cosh: { minArgs: 1, maxArgs: 1, snippet: "cosh()", description: "cosh(x) - applies hyperbolic cosinus function to value or each element of value" },
    cosine_similarity: { minArgs: 2, maxArgs: 2, snippet: "cosine_similarity()", description: "" },
    cossim: { minArgs: 2, maxArgs: 2, snippet: "cossim()", description: "" },
    count: { minArgs: 1, maxArgs: 1, snippet: "count()", description: "" },
    cov: { minArgs: 2, maxArgs: 2, snippet: "cov()", description: "" },
    crop: { minArgs: 3, maxArgs: 3, snippet: "crop()", description: "" },
    cross: { minArgs: 2, maxArgs: 2, snippet: "cross()", description: "" },
    cubic: { minArgs: 3, maxArgs: 3, snippet: "cubic()", description: "" },
    cubic_ease: { minArgs: 3, maxArgs: 3, snippet: "cubic_ease()", description: "" },
    cumprod: { minArgs: 1, maxArgs: 1, snippet: "cumprod()", description: "" },
    cumsum: { minArgs: 1, maxArgs: 1, snippet: "cumsum()", description: "" },
    dilate: { minArgs: 1, maxArgs: 2, snippet: "dilate()", description: "" },
    dist: { minArgs: 4, maxArgs: 4, snippet: "dist()", description: "" },
    distance: { minArgs: 4, maxArgs: 4, snippet: "distance()", description: "" },
    domain_warp: { minArgs: 4, maxArgs: 8, snippet: "domain_warp()", description: "" },
    domain_warp_noise: { minArgs: 4, maxArgs: 8, snippet: "domain_warp_noise()", description: "" },
    dot: { minArgs: 2, maxArgs: 2, snippet: "dot()", description: "" },
    edge: { minArgs: 1, maxArgs: 2, snippet: "edge()", description: "" },
    elastic: { minArgs: 3, maxArgs: 3, snippet: "elastic()", description: "" },
    elastic_ease: { minArgs: 3, maxArgs: 3, snippet: "elastic_ease()", description: "" },
    entropy: { minArgs: 1, maxArgs: 1, snippet: "entropy()", description: "" },
    erf: { minArgs: 1, maxArgs: 1, snippet: "erf()", description: "" },
    erfinv: { minArgs: 1, maxArgs: 1, snippet: "erfinv()", description: "" },
    erode: { minArgs: 1, maxArgs: 2, snippet: "erode()", description: "" },
    exp: { minArgs: 1, maxArgs: 1, snippet: "exp()", description: "exp(x) - applies e^x to value (per element)" },
    ezconv: { minArgs: 2, maxArgs: null, snippet: "ezconv()", description: "" },
    ezconvolution: { minArgs: 2, maxArgs: null, snippet: "ezconvolution()", description: "" },
    fft: { minArgs: 1, maxArgs: 1, snippet: "fft()", description: "" },
    find: { minArgs: 2, maxArgs: 2, snippet: "find()", description: "" },
    flatten: { minArgs: 1, maxArgs: 1, snippet: "flatten()", description: "" },
    flip: { minArgs: 2, maxArgs: 2, snippet: "flip()", description: "" },
    float: { minArgs: 1, maxArgs: 1, snippet: "float()", description: "" },
    floor: { minArgs: 1, maxArgs: 1, snippet: "floor()", description: "" },
    flow_ang: { minArgs: 1, maxArgs: 1, snippet: "flow_ang()", description: "" },
    flow_angle: { minArgs: 1, maxArgs: 1, snippet: "flow_angle()", description: "" },
    flow_apply: { minArgs: 2, maxArgs: 2, snippet: "flow_apply()", description: "" },
    flow_mag: { minArgs: 1, maxArgs: 1, snippet: "flow_mag()", description: "" },
    flow_magnitude: { minArgs: 1, maxArgs: 1, snippet: "flow_magnitude()", description: "" },
    flow_to_image: { minArgs: 1, maxArgs: 1, snippet: "flow_to_image()", description: "" },
    fract: { minArgs: 1, maxArgs: 1, snippet: "fract()", description: "" },
    gamma: { minArgs: 1, maxArgs: 1, snippet: "gamma()", description: "" },
    gaussian: { minArgs: 2, maxArgs: 3, snippet: "gaussian()", description: "" },
    gelu: { minArgs: 1, maxArgs: 1, snippet: "gelu()", description: "" },
    get_value: { minArgs: 2, maxArgs: 2, snippet: "get_value()", description: "" },
    hist: { minArgs: 4, maxArgs: 4, snippet: "hist()", description: "" },
    histogram: { minArgs: 4, maxArgs: 4, snippet: "histogram()", description: "" },
    hsv_to_rgb: { minArgs: 1, maxArgs: 4, snippet: "hsv_to_rgb()", description: "" },
    ifft: { minArgs: 1, maxArgs: 2, snippet: "ifft()", description: "" },
    int: { minArgs: 1, maxArgs: 1, snippet: "int()", description: "" },
    int_to_rgb: { minArgs: 1, maxArgs: 1, snippet: "int_to_rgb()", description: "" },
    interpolate_area: { minArgs: 2, maxArgs: 2, snippet: "interpolate_area()", description: "" },
    interpolate_linear: { minArgs: 2, maxArgs: 2, snippet: "interpolate_linear()", description: "" },
    interpolate_nearest: { minArgs: 2, maxArgs: 2, snippet: "interpolate_nearest()", description: "" },
    interpolate_nearest_exact: { minArgs: 2, maxArgs: 2, snippet: "interpolate_nearest_exact()", description: "" },
    join: { minArgs: 1, maxArgs: 2, snippet: "join()", description: "" },
    length: { minArgs: 1, maxArgs: 1, snippet: "length()", description: "" },
    lerp: { minArgs: 3, maxArgs: 3, snippet: "lerp()", description: "" },
    linspace: { minArgs: 3, maxArgs: 3, snippet: "linspace()", description: "" },
    ln: { minArgs: 1, maxArgs: 1, snippet: "ln()", description: "ln(x) - applies natural logarithm to value (per element). Negative numbers return NaN (not a number)" },
    log: { minArgs: 1, maxArgs: 1, snippet: "log()", description: "log(x) - applies base 10 logarithm to value (per element). Negative numbers return NaN (not a number)" },
    logspace: { minArgs: 4, maxArgs: 4, snippet: "logspace()", description: "" },
    lower: { minArgs: 1, maxArgs: 1, snippet: "lower()", description: "" },
    map: { minArgs: 2, maxArgs: null, snippet: "map()", description: "" },
    matmul: { minArgs: 2, maxArgs: 2, snippet: "matmul()", description: "" },
    mean: { minArgs: 1, maxArgs: 1, snippet: "mean()", description: "" },
    median: { minArgs: 1, maxArgs: 1, snippet: "median()", description: "" },
    mode: { minArgs: 1, maxArgs: 1, snippet: "mode()", description: "" },
    moment: { minArgs: 3, maxArgs: 3, snippet: "moment()", description: "" },
    morph_close: { minArgs: 1, maxArgs: 2, snippet: "morph_close()", description: "" },
    morph_open: { minArgs: 1, maxArgs: 2, snippet: "morph_open()", description: "" },
    motion_mask: { minArgs: 1, maxArgs: 1, snippet: "motion_mask()", description: "" },
    nan_to_num: { minArgs: 4, maxArgs: 4, snippet: "nan_to_num()", description: "" },
    noise: { minArgs: 1, maxArgs: 2, snippet: "noise()", description: "" },
    now: { minArgs: 0, maxArgs: 0, snippet: "now()", description: "" },
    nvl: { minArgs: 4, maxArgs: 4, snippet: "nvl()", description: "" },
    oklab_to_rgb: { minArgs: 1, maxArgs: 3, snippet: "oklab_to_rgb()", description: "" },
    overlay: { minArgs: 3, maxArgs: 4, snippet: "overlay()", description: "" },
    pad: { minArgs: 2, maxArgs: 2, snippet: "pad()", description: "" },
    percentile: { minArgs: 2, maxArgs: 2, snippet: "percentile()", description: "" },
    perlin: { minArgs: 2, maxArgs: 5, snippet: "perlin()", description: "" },
    perlin_noise: { minArgs: 2, maxArgs: 5, snippet: "perlin_noise()", description: "" },
    perm: { minArgs: 2, maxArgs: 2, snippet: "perm()", description: "" },
    permute: { minArgs: 2, maxArgs: 2, snippet: "permute()", description: "" },
    pinv: { minArgs: 1, maxArgs: 1, snippet: "pinv()", description: "" },
    plasma: { minArgs: 2, maxArgs: 5, snippet: "plasma()", description: "" },
    plasma_noise: { minArgs: 2, maxArgs: 5, snippet: "plasma_noise()", description: "" },
    popcnt: { minArgs: 1, maxArgs: 1, snippet: "popcnt()", description: "" },
    popcount: { minArgs: 1, maxArgs: 1, snippet: "popcount()", description: "" },
    pow: { minArgs: 2, maxArgs: 2, snippet: "pow()", description: "" },
    prcnt: { minArgs: 2, maxArgs: 2, snippet: "prcnt()", description: "" },
    print: { minArgs: 1, maxArgs: 1, snippet: "print()", description: "" },
    print_shape: { minArgs: 1, maxArgs: 1, snippet: "print_shape()", description: "" },
    pshp: { minArgs: 1, maxArgs: 1, snippet: "pshp()", description: "" },
    quantile: { minArgs: 2, maxArgs: 2, snippet: "quantile()", description: "" },
    quartil: { minArgs: 2, maxArgs: 2, snippet: "quartil()", description: "" },
    quartile: { minArgs: 2, maxArgs: 2, snippet: "quartile()", description: "" },
    rand: { minArgs: 1, maxArgs: 2, snippet: "rand()", description: "" },
    randb: { minArgs: 2, maxArgs: 3, snippet: "randb()", description: "" },
    randbeta: { minArgs: 3, maxArgs: 4, snippet: "randbeta()", description: "" },
    randc: { minArgs: 3, maxArgs: 4, snippet: "randc()", description: "" },
    rande: { minArgs: 2, maxArgs: 3, snippet: "rande()", description: "" },
    randg: { minArgs: 3, maxArgs: 4, snippet: "randg()", description: "" },
    randgumbel: { minArgs: 3, maxArgs: 4, snippet: "randgumbel()", description: "" },
    randchi2: { minArgs: 2, maxArgs: 3, snippet: "randchi2()", description: "" },
    randl: { minArgs: 3, maxArgs: 4, snippet: "randl()", description: "" },
    randln: { minArgs: 3, maxArgs: 4, snippet: "randln()", description: "" },
    randn: { minArgs: 1, maxArgs: 2, snippet: "randn()", description: "" },
    random_bernoulli: { minArgs: 2, maxArgs: 3, snippet: "random_bernoulli()", description: "" },
    random_beta: { minArgs: 3, maxArgs: 4, snippet: "random_beta()", description: "" },
    random_cauchy: { minArgs: 3, maxArgs: 4, snippet: "random_cauchy()", description: "" },
    random_exponential: { minArgs: 2, maxArgs: 3, snippet: "random_exponential()", description: "" },
    random_gamma: { minArgs: 3, maxArgs: 4, snippet: "random_gamma()", description: "" },
    random_gumbel: { minArgs: 3, maxArgs: 4, snippet: "random_gumbel()", description: "" },
    random_chi2: { minArgs: 2, maxArgs: 3, snippet: "random_chi2()", description: "" },
    random_laplace: { minArgs: 3, maxArgs: 4, snippet: "random_laplace()", description: "" },
    random_log_normal: { minArgs: 3, maxArgs: 4, snippet: "random_log_normal()", description: "" },
    random_normal: { minArgs: 1, maxArgs: 2, snippet: "random_normal()", description: "" },
    random_poisson: { minArgs: 2, maxArgs: 3, snippet: "random_poisson()", description: "" },
    random_studentt: { minArgs: 2, maxArgs: 3, snippet: "random_studentt()", description: "" },
    random_uniform: { minArgs: 1, maxArgs: 2, snippet: "random_uniform()", description: "" },
    random_weibull: { minArgs: 3, maxArgs: 4, snippet: "random_weibull()", description: "" },
    randp: { minArgs: 2, maxArgs: 3, snippet: "randp()", description: "" },
    randt: { minArgs: 2, maxArgs: 3, snippet: "randt()", description: "" },
    randu: { minArgs: 1, maxArgs: 2, snippet: "randu()", description: "" },
    randw: { minArgs: 3, maxArgs: 4, snippet: "randw()", description: "" },
    range: { minArgs: 3, maxArgs: 3, snippet: "range()", description: "" },
    relu: { minArgs: 1, maxArgs: null, snippet: "relu()", description: "" },
    remap: { minArgs: 5, maxArgs: 5, snippet: "remap()", description: "" },
    replace: { minArgs: 3, maxArgs: 3, snippet: "replace()", description: "" },
    reshape: { minArgs: 2, maxArgs: 2, snippet: "reshape()", description: "" },
    rgb_to_cielab: { minArgs: 1, maxArgs: 3, snippet: "rgb_to_cielab()", description: "" },
    rgb_to_hsv: { minArgs: 1, maxArgs: 4, snippet: "rgb_to_hsv()", description: "" },
    rgb_to_int: { minArgs: 1, maxArgs: 3, snippet: "rgb_to_int()", description: "" },
    rgb_to_oklab: { minArgs: 1, maxArgs: 3, snippet: "rgb_to_oklab()", description: "" },
    ridged: { minArgs: 2, maxArgs: 5, snippet: "ridged()", description: "" },
    ridged_noise: { minArgs: 2, maxArgs: 5, snippet: "ridged_noise()", description: "" },
    rife: { minArgs: 4, maxArgs: 5, snippet: "rife()", description: "" },
    roll: { minArgs: 2, maxArgs: 3, snippet: "roll()", description: "" },
    round: { minArgs: 1, maxArgs: 1, snippet: "round()", description: "" },
    rshp: { minArgs: 2, maxArgs: 2, snippet: "rshp()", description: "" },
    select: { minArgs: 2, maxArgs: 2, snippet: "select()", description: "" },
    shape: { minArgs: 1, maxArgs: 1, snippet: "shape()", description: "" },
    shuffle: { minArgs: 2, maxArgs: 2, snippet: "shuffle()", description: "" },
    sigm: { minArgs: 1, maxArgs: 1, snippet: "sigm()", description: "" },
    sign: { minArgs: 1, maxArgs: 1, snippet: "sign()", description: "" },
    sin: { minArgs: 1, maxArgs: 1, snippet: "sin()", description: "sin(x) - applies sinus function to value or each element of value" },
    sine: { minArgs: 3, maxArgs: 3, snippet: "sine()", description: "" },
    sine_ease: { minArgs: 3, maxArgs: 3, snippet: "sine_ease()", description: "" },
    sinh: { minArgs: 1, maxArgs: 1, snippet: "sinh()", description: "sinh(x) - applies hyperbolic sinus function to value or each element of value" },
    smax: { minArgs: 1, maxArgs: null, snippet: "smax()", description: "" },
    smin: { minArgs: 1, maxArgs: null, snippet: "smin()", description: "" },
    smootherstep: { minArgs: 3, maxArgs: 3, snippet: "smootherstep()", description: "" },
    smoothstep: { minArgs: 3, maxArgs: 3, snippet: "smoothstep()", description: "" },
    snorm: { minArgs: 1, maxArgs: 1, snippet: "snorm()", description: "snorm(x) - returns a frobenius norm of the tensor as a float number" },
    softmax: { minArgs: 1, maxArgs: 2, snippet: "softmax()", description: "" },
    softmin: { minArgs: 1, maxArgs: 2, snippet: "softmin()", description: "" },
    softplus: { minArgs: 1, maxArgs: 1, snippet: "softplus()", description: "" },
    sort: { minArgs: 1, maxArgs: 1, snippet: "sort()", description: "" },
    split: { minArgs: 1, maxArgs: 2, snippet: "split()", description: "" },
    sqrt: { minArgs: 1, maxArgs: 1, snippet: "sqrt()", description: "sqrt(x) - applies sqere root per element. Negative numbers return NaN (not a number)" },
    stack_clear: { minArgs: 1, maxArgs: 1, snippet: "stack_clear()", description: "" },
    stack_get: { minArgs: 1, maxArgs: 1, snippet: "stack_get()", description: "" },
    stack_has: { minArgs: 1, maxArgs: 1, snippet: "stack_has()", description: "" },
    stack_pop: { minArgs: 1, maxArgs: 1, snippet: "stack_pop()", description: "" },
    stack_push: { minArgs: 2, maxArgs: 2, snippet: "stack_push()", description: "" },
    std: { minArgs: 1, maxArgs: 1, snippet: "std()", description: "" },
    step: { minArgs: 2, maxArgs: 2, snippet: "step()", description: "" },
    substr: { minArgs: 2, maxArgs: 3, snippet: "substr()", description: "" },
    substring: { minArgs: 2, maxArgs: 3, snippet: "substring()", description: "" },
    sum: { minArgs: 1, maxArgs: 1, snippet: "sum()", description: "" },
    swap: { minArgs: 4, maxArgs: 4, snippet: "swap()", description: "" },
    tan: { minArgs: 1, maxArgs: 1, snippet: "tan()", description: "tan(x) - applies tangents function to value or each element of value" },
    tanh: { minArgs: 1, maxArgs: 1, snippet: "tanh()", description: "tanh(x) - applies hyperbolic tangents function to value or each element of value" },
    tensor: { minArgs: 2, maxArgs: 3, snippet: "tensor()", description: "" },
    text_image: { minArgs: 3, maxArgs: 9, snippet: "text_image()", description: "" },
    timestamp: { minArgs: 0, maxArgs: 0, snippet: "timestamp()", description: "" },
    tmax: { minArgs: 2, maxArgs: 2, snippet: "tmax()", description: "tmax(x,y) - elementwise maximum of tensor or list. max(x,y) when inputs are floats" },
    tmin: { minArgs: 2, maxArgs: 2, snippet: "tmin()", description: "" },
    tnorm: { minArgs: 1, maxArgs: 2, snippet: "tnorm()", description: "tnorm(x,[dim]) - normalises tensor or list by multiplication such that sum(x^2)==1.0 for each slice. The slice is last dimension of the tensor when not provided. If dim = None, it behaves the same as snorm." },
    topk: { minArgs: 2, maxArgs: 2, snippet: "topk()", description: "" },
    topk_ind: { minArgs: 2, maxArgs: 2, snippet: "topk_ind()", description: "" },
    topk_indices: { minArgs: 2, maxArgs: 2, snippet: "topk_indices()", description: "" },
    trim: { minArgs: 1, maxArgs: 1, snippet: "trim()", description: "" },
    turbulence: { minArgs: 2, maxArgs: 5, snippet: "turbulence()", description: "" },
    unique: { minArgs: 1, maxArgs: 1, snippet: "unique()", description: "" },
    upper: { minArgs: 1, maxArgs: 1, snippet: "upper()", description: "" },
    var: { minArgs: 1, maxArgs: 1, snippet: "var()", description: "" },
    voronoi: { minArgs: 2, maxArgs: 5, snippet: "voronoi()", description: "" },
    voronoi_noise: { minArgs: 2, maxArgs: 5, snippet: "voronoi_noise()", description: "" },
    where: { minArgs: 3, maxArgs: 3, snippet: "where()", description: "" },
    worley: { minArgs: 2, maxArgs: 5, snippet: "worley()", description: "" },
};