// Generated automatically by compile.ps1. Do not edit.

export const KEYWORDS = new Set([
"break", "continue", "else", "for", "if", "in", "none", "null", "return", "while"
]);

export const CONSTANTS = new Set([
"e", "pi"
]);

export const FUNCTIONS = new Set([
"abs", "acos", "acosh", "add_key", "all", "angle", "any", "append", "argmax", "argmin", "argsort", "as_nested", "as_nested_tensor", "asin", "asinh", "atan", "atan2", "atanh", "band", "batch_shuffle", "bitcount", "bitwise_and", "bitwise_not", "bitwise_or", "bitwise_xor", "blur", "bnot", "bor", "botk", "botk_ind", "botk_indices", "bxor", "cat", "ceil", "cellular", "cellular_noise", "cielab_to_rgb", "clamp", "cnt", "concat", "concatenate", "conv", "convolution", "coordinates", "coords", "corr", "correlation", "cos", "cosh", "cosine_similarity", "cossim", "count", "cov", "crop", "cross", "cubic", "cubic_ease", "cumprod", "cumsum", "diag", "diagonal_matrix", "dilate", "dist", "distance", "domain_warp", "domain_warp_noise", "dot", "edge", "elastic", "elastic_ease", "endswith", "entropy", "erf", "erfinv", "erode", "exp", "ezconv", "ezconvolution", "fft", "find", "flatten", "flip", "float", "floor", "flow_ang", "flow_angle", "flow_apply", "flow_mag", "flow_magnitude", "flow_to_image", "fract", "gamma", "gaussian", "gelu", "get_value", "hist", "histogram", "hsv_to_rgb", "ifft", "int", "int_to_rgb", "interpolate_area", "interpolate_linear", "interpolate_nearest", "interpolate_nearest_exact", "join", "keys", "length", "lerp", "linspace", "ln", "log", "logspace", "lower", "map", "matmul", "mean", "median", "mode", "moment", "morph_close", "morph_open", "motion_mask", "nan_to_num", "noise", "now", "nvl", "oklab_to_rgb", "overlay", "pad", "percentile", "perlin", "perlin_noise", "perm", "permute", "pinv", "plasma", "plasma_noise", "popcnt", "popcount", "pow", "prcnt", "print", "print_shape", "pshp", "quantile", "quartil", "quartile", "rand", "randb", "randbeta", "randc", "randchi2", "rande", "randg", "randgumbel", "randl", "randln", "randn", "random_bernoulli", "random_beta", "random_cauchy", "random_chi2", "random_exponential", "random_gamma", "random_gumbel", "random_laplace", "random_log_normal", "random_normal", "random_poisson", "random_studentt", "random_uniform", "random_weibull", "randp", "randt", "randu", "randw", "range", "relu", "remap", "remove_key", "repeat", "replace", "reshape", "rgb_to_cielab", "rgb_to_hsv", "rgb_to_int", "rgb_to_oklab", "ridged", "ridged_noise", "rife", "rm_key", "roll", "round", "rshp", "select", "shape", "shuffle", "sigm", "sign", "sin", "sine", "sine_ease", "singular_value_decomposition", "sinh", "smax", "smin", "smootherstep", "smoothstep", "snorm", "softmax", "softmin", "softplus", "sort", "split", "sqrt", "squeeze", "stack_clear", "stack_get", "stack_has", "stack_pop", "stack_push", "startswith", "std", "step", "substr", "substring", "sum", "svd", "swap", "tan", "tanh", "tensor", "text_image", "timestamp", "tmax", "tmin", "tnorm", "topk", "topk_ind", "topk_indices", "trim", "turbulence", "unique", "unsqueeze", "upper", "var", "voronoi", "voronoi_noise", "where", "worley"
]);

export const FUNCTION_META = {
    "sin": { minArgs: 1, maxArgs: 1, snippet: "sin(x)", description: "applies sinus function to value or each element of value" },
    "cos": { minArgs: 1, maxArgs: 1, snippet: "cos(x)", description: "applies cosinus function to value or each element of value" },
    "tan": { minArgs: 1, maxArgs: 1, snippet: "tan(x)", description: "applies tangents function to value or each element of value" },
    "asin": { minArgs: 1, maxArgs: 1, snippet: "asin(x)", description: "applies arcus sinus function to value or each element of value" },
    "acos": { minArgs: 1, maxArgs: 1, snippet: "acos(x)", description: "applies arcus cosinus function to value or each element of value" },
    "atan": { minArgs: 1, maxArgs: 1, snippet: "atan(x)", description: "applies arcus tangents function to value or each element of value" },
    "atan2": { minArgs: 2, maxArgs: 2, snippet: "atan2(y, x)", description: "computes the arc tangent of y/x, using the signs of both arguments to determine the quadrant" },
    "sinh": { minArgs: 1, maxArgs: 1, snippet: "sinh(x)", description: "applies hyperbolic sinus function to value or each element of value" },
    "cosh": { minArgs: 1, maxArgs: 1, snippet: "cosh(x)", description: "applies hyperbolic cosinus function to value or each element of value" },
    "tanh": { minArgs: 1, maxArgs: 1, snippet: "tanh(x)", description: "applies hyperbolic tangents function to value or each element of value" },
    "asinh": { minArgs: 1, maxArgs: 1, snippet: "asinh(x)", description: "applies hyperbolic arcus sinus function to value or each element of value" },
    "acosh": { minArgs: 1, maxArgs: 1, snippet: "acosh(x)", description: "applies hyperbolic arcus cosinus function to value or each element of value" },
    "atanh": { minArgs: 1, maxArgs: 1, snippet: "atanh(x)", description: "applies hyperbolic arcus tangents function to value or each element of value" },
    "abs": { minArgs: 1, maxArgs: 1, snippet: "abs(x)", description: "applies per element absolute value function. Same as |x| for numbers." },
    "sqrt": { minArgs: 1, maxArgs: 1, snippet: "sqrt(x)", description: "applies sqere root per element. Negative numbers return NaN (not a number)" },
    "ln": { minArgs: 1, maxArgs: 1, snippet: "ln(x)", description: "applies natural logarithm to value (per element). Negative numbers return NaN (not a number)" },
    "log": { minArgs: 1, maxArgs: 1, snippet: "log(x)", description: "applies base 10 logarithm to value (per element). Negative numbers return NaN (not a number)" },
    "exp": { minArgs: 1, maxArgs: 1, snippet: "exp(x)", description: "applies e^x to value (per element)" },
    "smin": { minArgs: 1, maxArgs: null, snippet: "smin(x, ...)", description: "computes the minimum of inputs or elements. Tensors must have the same size or be broadcastable to same size. When called as smin(x, dims) with x a tensor/list, reduces x along dims (a single dim or list of dims) instead." },
    "smax": { minArgs: 1, maxArgs: null, snippet: "smax(x, ...)", description: "computes the maximum of inputs or elements. Tensors must have the same size or be broadcastable to same size. When called as smax(x, dims) with x a tensor/list, reduces x along dims (a single dim or list of dims) instead." },
    "tmin": { minArgs: 2, maxArgs: 2, snippet: "tmin(x, y)", description: "elementwise minimum of tensor or list. min(x,y) when inputs are floats" },
    "tmax": { minArgs: 2, maxArgs: 2, snippet: "tmax(x, y)", description: "elementwise maximum of tensor or list. max(x,y) when inputs are floats" },
    "tnorm": { minArgs: 1, maxArgs: 2, snippet: "tnorm(x, dim)", description: "normalises tensor or list by multiplication such that sum(x^2)==1.0 for each slice. Defaults to the last dimension; dim selects a different slicing dimension." },
    "snorm": { minArgs: 1, maxArgs: 2, snippet: "snorm(x, dim)", description: "frobenius norm of tensor. Along dimension if dimension specified. Dimension can be a list. Defaults to no dimension." },
    "floor": { minArgs: 1, maxArgs: 1, snippet: "floor(x)", description: "returns the largest integer less than or equal to x" },
    "ceil": { minArgs: 1, maxArgs: 1, snippet: "ceil(x)", description: "returns the smallest integer greater than or equal to x" },
    "round": { minArgs: 1, maxArgs: 1, snippet: "round(x)", description: "rounds x to the nearest integer" },
    "gamma": { minArgs: 1, maxArgs: 1, snippet: "gamma(x)", description: "computes the gamma function (per element)" },
    "pow": { minArgs: 2, maxArgs: 2, snippet: "pow(x, y)", description: "computes x raised to the power of y" },
    "sigm": { minArgs: 1, maxArgs: 1, snippet: "sigm(x)", description: "applies the sigmoid function: 1 / (1 + exp(-x))" },
    "clamp": { minArgs: 3, maxArgs: 3, snippet: "clamp(x, min, max)", description: "clamps x between min and max per element" },
    "fft": { minArgs: 1, maxArgs: 1, snippet: "fft(x)", description: "computes  fast Fourier transform of x" },
    "ifft": { minArgs: 1, maxArgs: 2, snippet: "ifft(x, shape)", description: "inverse fast Fourier transform of x. shape (defaults to the node's tensor shape) sizes the K/Kx/Ky/.../frequency variables made available while evaluating x, it does not resize x itself." },
    "angle": { minArgs: 1, maxArgs: 1, snippet: "angle(x)", description: "returns the angle of a complex number or vector" },
    "print": { minArgs: 1, maxArgs: 1, snippet: "print(x)", description: "prints the value of x to the console while passing output unchanged" },
    "print_shape": { minArgs: 1, maxArgs: 1, snippet: "print_shape(x)", description: "prints the shape of the tensor x" },
    "pshp": { minArgs: 1, maxArgs: 1, snippet: "pshp(x)", description: "prints the shape of the tensor x" },
    "nvl": { minArgs: 4, maxArgs: 4, snippet: "nvl(x, nan, pos_inf, neg_inf)", description: "null value replacement - inspired by NVL" },
    "nan_to_num": { minArgs: 4, maxArgs: 4, snippet: "nan_to_num(x, nan, pos_inf, neg_inf)", description: "null value replacement - inspired by NVL" },
    "lerp": { minArgs: 3, maxArgs: 3, snippet: "lerp(a, b, t)", description: "linear interpolation between a and b by t per element. t can be float or tensor." },
    "step": { minArgs: 2, maxArgs: 2, snippet: "step(x, edge)", description: "returns 0 if x < edge, else 1" },
    "smoothstep": { minArgs: 3, maxArgs: 3, snippet: "smoothstep(x, edge0, edge1)", description: "smooth interpolation between edge0 and edge1" },
    "fract": { minArgs: 1, maxArgs: 1, snippet: "fract(x)", description: "returns the fractional part of x: x - floor(x)" },
    "relu": { minArgs: 1, maxArgs: 1, snippet: "relu(x)", description: "applies rectified linear unit function: max(0, x)" },
    "softplus": { minArgs: 1, maxArgs: 1, snippet: "softplus(x)", description: "applies the softplus function: ln(1 + exp(x))" },
    "gelu": { minArgs: 1, maxArgs: 1, snippet: "gelu(x)", description: "applies the Gaussian Error Linear Unit (GELU) activation function" },
    "sign": { minArgs: 1, maxArgs: 1, snippet: "sign(x)", description: "returns the sign of x: -1, 0, or 1" },
    "map": { minArgs: 2, maxArgs: 4, snippet: "map(tensor, coord1, coord2, coord3)", description: "samples/remaps input tensor using coordinates" },
    "ezconvolution": { minArgs: 2, maxArgs: 3, snippet: "ezconvolution(tensor, kernel_sizes..., kernel)", description: "applies convolution with kernel. Attempts to correctly convolve over size dimensions." },
    "ezconv": { minArgs: 2, maxArgs: 3, snippet: "ezconv(tensor, kernel_sizes..., kernel)", description: "applies convolution with kernel. Attempts to correctly convolve over size dimensions." },
    "convolution": { minArgs: 2, maxArgs: 3, snippet: "convolution(tensor, kernel_sizes..., kernel)", description: "applies convolution with kernel. Expects [batch,channel, ...]" },
    "conv": { minArgs: 2, maxArgs: 3, snippet: "conv(tensor, kernel_sizes..., kernel)", description: "applies convolution with kernel. Expects [batch,channel, ...]" },
    "swap": { minArgs: 4, maxArgs: 4, snippet: "swap(x, dim, idx1, idx2)", description: "swaps elements along dim between idx1 and idx2" },
    "permute": { minArgs: 2, maxArgs: 2, snippet: "permute(x, dims)", description: "permutes the dimensions of tensor x according to dims" },
    "perm": { minArgs: 2, maxArgs: 2, snippet: "perm(x, dims)", description: "permutes the dimensions of tensor x according to dims" },
    "reshape": { minArgs: 2, maxArgs: 2, snippet: "reshape(x, shape)", description: "reshapes tensor x to the specified shape" },
    "rshp": { minArgs: 2, maxArgs: 2, snippet: "rshp(x, shape)", description: "reshapes tensor x to the specified shape" },
    "range": { minArgs: 3, maxArgs: 3, snippet: "range(start, stop, step)", description: "creates a range of values between start (inclusive) and stop (exclusive) using step. Use linspace if you want value count." },
    "linspace": { minArgs: 3, maxArgs: 3, snippet: "linspace(start, stop, num)", description: "creates num linearly spaced values from start to stop (inclusive). Use range if you want to control the step between values." },
    "logspace": { minArgs: 4, maxArgs: 4, snippet: "logspace(start, stop, num, base)", description: "creates logarithmically spaced values" },
    "topk": { minArgs: 2, maxArgs: 2, snippet: "topk(x, k)", description: "returns the k largest elements of x. For tensors it keeps them in place." },
    "botk": { minArgs: 2, maxArgs: 2, snippet: "botk(x, k)", description: "returns the k smallest elements of x.  For tensors it keeps them in place." },
    "pinv": { minArgs: 1, maxArgs: 1, snippet: "pinv(x)", description: "computes the permutative inverse of a list x (list must have uniqe elements) -- TODO: CHECK --" },
    "sum": { minArgs: 1, maxArgs: 2, snippet: "sum(x, dims)", description: "computes the sum of elements of x, optionally along one or more dimensions" },
    "mean": { minArgs: 1, maxArgs: 1, snippet: "mean(x)", description: "computes the arithmetic mean of elements of x" },
    "std": { minArgs: 1, maxArgs: 1, snippet: "std(x)", description: "computes the standard deviation of elements of x" },
    "var": { minArgs: 1, maxArgs: 1, snippet: "var(x)", description: "computes the variance of elements of x" },
    "quartile": { minArgs: 2, maxArgs: 2, snippet: "quartile(x, q)", description: "computes the q-th quartile of x" },
    "quartil": { minArgs: 2, maxArgs: 2, snippet: "quartil(x, q)", description: "computes the q-th quartile of x" },
    "percentile": { minArgs: 2, maxArgs: 2, snippet: "percentile(x, p)", description: "computes the p-th percentile of x" },
    "prcnt": { minArgs: 2, maxArgs: 2, snippet: "prcnt(x, p)", description: "computes the p-th percentile of x" },
    "quantile": { minArgs: 2, maxArgs: 2, snippet: "quantile(x, q)", description: "computes the q-th quantile of x" },
    "dot": { minArgs: 2, maxArgs: 2, snippet: "dot(x, y)", description: "computes the dot product of x and y after flattening both to 1D. Use cross(x, y) if you need a per-vector product with the last dimension kept." },
    "moment": { minArgs: 3, maxArgs: 3, snippet: "moment(x, a, k)", description: "computes the k-th moment of x around a" },
    "erf": { minArgs: 1, maxArgs: 1, snippet: "erf(x)", description: "computes the error function (torch.erf)" },
    "erfinv": { minArgs: 1, maxArgs: 1, snippet: "erfinv(x)", description: "computes the inverse error function (torch.erfinv)" },
    "any": { minArgs: 1, maxArgs: 1, snippet: "any(x)", description: "returns 1 if any element of x is non-zero otherwise 0" },
    "all": { minArgs: 1, maxArgs: 1, snippet: "all(x)", description: "returns 1 if all elements of x are non-zero otherwise 0" },
    "edge": { minArgs: 1, maxArgs: 2, snippet: "edge(x, matrix_size)", description: "detects edges in x. Matrix size denotes the size of edge detection matrix." },
    "blur": { minArgs: 2, maxArgs: 3, snippet: "blur(x, sigma, reshape)", description: "applies a Gaussian blur to x with specified sigma. if reshape has value of 1.0, then it tries orienting the input such that channel is in the direction of filter. Otherwise it expect color dimension to be the last." },
    "gaussian": { minArgs: 2, maxArgs: 3, snippet: "gaussian(x, sigma, reshape)", description: "applies a Gaussian blur to x with specified sigma. if reshape has value of 1.0, then it tries orienting the input such that channel is in the direction of filter. Otherwise it expect color dimension to be the last." },
    "median": { minArgs: 1, maxArgs: 1, snippet: "median(x)", description: "computes the median of elements of x" },
    "mode": { minArgs: 1, maxArgs: 1, snippet: "mode(x)", description: "computes the mode of elements of x" },
    "cumsum": { minArgs: 1, maxArgs: 2, snippet: "cumsum(x, dim)", description: "computes the cumulative sum, defaulting to the first dimension." },
    "cumprod": { minArgs: 1, maxArgs: 1, snippet: "cumprod(x)", description: "computes the cumulative product over first dimension." },
    "topk_ind": { minArgs: 2, maxArgs: 2, snippet: "topk_ind(x, k)", description: "returns the indices of the k largest elements of x" },
    "topk_indices": { minArgs: 2, maxArgs: 2, snippet: "topk_indices(x, k)", description: "returns the indices of the k largest elements of x" },
    "botk_ind": { minArgs: 2, maxArgs: 2, snippet: "botk_ind(x, k)", description: "returns the indices of the k smallest elements of x" },
    "botk_indices": { minArgs: 2, maxArgs: 2, snippet: "botk_indices(x, k)", description: "returns the indices of the k smallest elements of x" },
    "cubic_ease": { minArgs: 3, maxArgs: 3, snippet: "cubic_ease(a, b, t)", description: "cubic ease between a and b" },
    "cubic": { minArgs: 3, maxArgs: 3, snippet: "cubic(a, b, t)", description: "cubic ease between a and b" },
    "elastic_ease": { minArgs: 3, maxArgs: 3, snippet: "elastic_ease(a, b, t)", description: "elastic ease between a and b" },
    "elastic": { minArgs: 3, maxArgs: 3, snippet: "elastic(a, b, t)", description: "elastic ease between a and b" },
    "sine_ease": { minArgs: 3, maxArgs: 3, snippet: "sine_ease(a, b, t)", description: "sine easing between a and b" },
    "sine": { minArgs: 3, maxArgs: 3, snippet: "sine(a, b, t)", description: "sine easing between a and b" },
    "smootherstep": { minArgs: 3, maxArgs: 3, snippet: "smootherstep(x, edge0, edge1)", description: "smoother interpolation between edge0 and edge1" },
    "dist": { minArgs: 4, maxArgs: 4, snippet: "dist(x1, y1, x2, y2)", description: "computes Euclidean distance between (x1, y1) and (x2, y2)" },
    "distance": { minArgs: 4, maxArgs: 4, snippet: "distance(x1, y1, x2, y2)", description: "computes Euclidean distance between (x1, y1) and (x2, y2)" },
    "remap": { minArgs: 5, maxArgs: 5, snippet: "remap(v, i_min, i_max, o_min, o_max)", description: "remaps values from input range to output range" },
    "cossim": { minArgs: 2, maxArgs: 2, snippet: "cossim(x, y)", description: "computes the cosine similarity between x and y." },
    "cosine_similarity": { minArgs: 2, maxArgs: 2, snippet: "cosine_similarity(x, y)", description: "computes the cosine similarity between x and y." },
    "count": { minArgs: 1, maxArgs: 1, snippet: "count(x)", description: "returns the number of elements in x" },
    "cnt": { minArgs: 1, maxArgs: 1, snippet: "cnt(x)", description: "returns the number of elements in x" },
    "length": { minArgs: 1, maxArgs: 1, snippet: "length(x)", description: "returns the number of elements in x" },
    "keys": { minArgs: 1, maxArgs: 1, snippet: "keys(x)", description: "returns a list of dictionary keys in insertion order" },
    "repeat": { minArgs: 2, maxArgs: 3, snippet: "repeat(x, count, dims)", description: "repeats tensor elements; count may be scalar or per-dim list" },
    "flatten": { minArgs: 1, maxArgs: 1, snippet: "flatten(x)", description: "flattens tensor into a 1D tensor" },
    "append": { minArgs: 2, maxArgs: 2, snippet: "append(x, y)", description: "appends y to the end of x. If inputs are tensors use concatenate(x,...,dim)" },
    "get_value": { minArgs: 1, maxArgs: 1, snippet: "get_value(slot)", description: "returns the value at slot from stack" },
    "flow_apply": { minArgs: 2, maxArgs: 2, snippet: "flow_apply(image, flow)", description: "applies optical flow to an image" },
    "batch_shuffle": { minArgs: 2, maxArgs: 2, snippet: "batch_shuffle(x, indices)", description: "shuffles and duplicates or skips the batch dimension of x according to indices" },
    "shuffle": { minArgs: 2, maxArgs: 2, snippet: "shuffle(x, indices)", description: "shuffles and duplicates or skips the batch dimension of x according to indices" },
    "select": { minArgs: 2, maxArgs: 2, snippet: "select(x, indices)", description: "shuffles and duplicates or skips the batch dimension of x according to indices" },
    "motion_mask": { minArgs: 1, maxArgs: 1, snippet: "motion_mask(x)", description: "generates a motion mask from optical flow" },
    "flow_to_image": { minArgs: 1, maxArgs: 1, snippet: "flow_to_image(x)", description: "converts optical flow x to an RGB image. Up-Down is blue-yellow Left-right green-magenta." },
    "flow_mag": { minArgs: 1, maxArgs: 1, snippet: "flow_mag(x)", description: "computes the magnitude of optical flow (or any other structure with last dimension of 2)" },
    "flow_magnitude": { minArgs: 1, maxArgs: 1, snippet: "flow_magnitude(x)", description: "computes the magnitude of optical flow (or any other structure with last dimension of 2)" },
    "flow_ang": { minArgs: 1, maxArgs: 1, snippet: "flow_ang(x)", description: "computes the angle of optical flow (basically angle() but real and imaginery is separate in 2 dimensions)" },
    "flow_angle": { minArgs: 1, maxArgs: 1, snippet: "flow_angle(x)", description: "computes the angle of optical flow (basically angle() but real and imaginery is separate in 2 dimensions)" },
    "where": { minArgs: 3, maxArgs: 3, snippet: "where(condition, x, y)", description: "returns x if condition is true, else y. Runs per element." },
    "histogram": { minArgs: 4, maxArgs: 4, snippet: "histogram(x, bins, min, max)", description: "computes histogram" },
    "hist": { minArgs: 4, maxArgs: 4, snippet: "hist(x, bins, min, max)", description: "computes histogram" },
    "overlay": { minArgs: 3, maxArgs: 4, snippet: "overlay(base, overlay, offset, opacity)", description: "overlays overlay on base at offset. Opacity controls blending. It can be tensor or float. If it is tensor it should be the same shape as overlay." },
    "pad": { minArgs: 2, maxArgs: 2, snippet: "pad(x, padding)", description: "pads tensor x with specified padding (dim 0 neg, dim 0 pos, dim 1 ...)" },
    "cross": { minArgs: 2, maxArgs: 2, snippet: "cross(x, y)", description: "computes the cross product of x and y. Last dimension must be 3" },
    "matmul": { minArgs: 2, maxArgs: 2, snippet: "matmul(x, y)", description: "computes the matrix multiplication of x and y" },
    "rife": { minArgs: 2, maxArgs: 5, snippet: "rife(image1, image2, tiling_size, iterations, multi_scale)", description: "computes the optical flow field ([H, W, 2]) between image1 and image2 using a RAFT-based model" },
    "bnot": { minArgs: 1, maxArgs: 1, snippet: "bnot(x)", description: "computes the bitwise NOT" },
    "bitwise_not": { minArgs: 1, maxArgs: 1, snippet: "bitwise_not(x)", description: "computes the bitwise NOT" },
    "bitcount": { minArgs: 1, maxArgs: 1, snippet: "bitcount(x)", description: "returns the number of set bits" },
    "popcount": { minArgs: 1, maxArgs: 1, snippet: "popcount(x)", description: "returns the number of set bits" },
    "popcnt": { minArgs: 1, maxArgs: 1, snippet: "popcnt(x)", description: "returns the number of set bits" },
    "shape": { minArgs: 1, maxArgs: 1, snippet: "shape(x)", description: "returns the shape of tensor as a list" },
    "band": { minArgs: 2, maxArgs: 2, snippet: "band(x, y)", description: "computes the element-wise bitwise AND of x and y" },
    "bitwise_and": { minArgs: 2, maxArgs: 2, snippet: "bitwise_and(x, y)", description: "computes the element-wise bitwise AND of x and y" },
    "bxor": { minArgs: 2, maxArgs: 2, snippet: "bxor(x, y)", description: "computes the element-wise bitwise XOR of x and y" },
    "bitwise_xor": { minArgs: 2, maxArgs: 2, snippet: "bitwise_xor(x, y)", description: "computes the element-wise bitwise XOR of x and y" },
    "bor": { minArgs: 2, maxArgs: 2, snippet: "bor(x, y)", description: "computes the element-wise bitwise OR of x and y" },
    "bitwise_or": { minArgs: 2, maxArgs: 2, snippet: "bitwise_or(x, y)", description: "computes the element-wise bitwise OR of x and y" },
    "tensor": { minArgs: 1, maxArgs: 3, snippet: "tensor(shape, value, dtype_template)", description: "creates a tensor with specified shape and optional value/type. Default value is 0 and default format FP32" },
    "add_key": { minArgs: 3, maxArgs: 3, snippet: "add_key(dict, key, value)", description: "adds or replaces a dictionary entry and returns the updated dictionary" },
    "remove_key": { minArgs: 2, maxArgs: 2, snippet: "remove_key(dict, key)", description: "removes a dictionary entry and returns the updated dictionary" },
    "rm_key": { minArgs: 2, maxArgs: 2, snippet: "rm_key(dict, key)", description: "removes a dictionary entry and returns the updated dictionary" },
    "stack_push": { minArgs: 2, maxArgs: 2, snippet: "stack_push(slot, val)", description: "pushes val onto the end of slot stack" },
    "stack_pop": { minArgs: 1, maxArgs: 1, snippet: "stack_pop(slot)", description: "removes and returns the last element of slot stack" },
    "stack_clear": { minArgs: 1, maxArgs: 1, snippet: "stack_clear(slot)", description: "clears the contents of slot stack" },
    "stack_has": { minArgs: 1, maxArgs: 1, snippet: "stack_has(slot)", description: "returns 1.0 if slot exists in stack and is not empty else returns 0.0" },
    "stack_get": { minArgs: 1, maxArgs: 1, snippet: "stack_get(slot)", description: "returns the last pushed value in slot without popping it" },
    "cat": { minArgs: 3, maxArgs: null, snippet: "cat(x1, x2, ..., dim)", description: "concatenates tensors along the specified dimension" },
    "concat": { minArgs: 3, maxArgs: null, snippet: "concat(x1, x2, ..., dim)", description: "concatenates tensors along the specified dimension" },
    "concatenate": { minArgs: 3, maxArgs: null, snippet: "concatenate(x1, x2, ..., dim)", description: "concatenates tensors along the specified dimension" },
    "int": { minArgs: 1, maxArgs: 1, snippet: "int(x)", description: "casts x to integer" },
    "float": { minArgs: 1, maxArgs: 1, snippet: "float(x)", description: "casts x to float" },
    "upper": { minArgs: 1, maxArgs: 1, snippet: "upper(x)", description: "converts string to uppercase" },
    "lower": { minArgs: 1, maxArgs: 1, snippet: "lower(x)", description: "converts string to lowercase" },
    "trim": { minArgs: 1, maxArgs: 1, snippet: "trim(x)", description: "removes leading and trailing whitespace from string" },
    "split": { minArgs: 1, maxArgs: 2, snippet: "split(x, delimiter)", description: "splits string to list of strings based on delimiter. Default is space." },
    "join": { minArgs: 1, maxArgs: 2, snippet: "join(x, separator)", description: "joins strings in list using separator. Defalut separator is \"\". If you want to join tensors use concatinate(...)" },
    "substring": { minArgs: 2, maxArgs: 3, snippet: "substring(s, start, length)", description: "returns length characters of s starting at start. If length is not supplied, it returns the rest of the string" },
    "substr": { minArgs: 2, maxArgs: 3, snippet: "substr(s, start, length)", description: "returns length characters of s starting at start. If length is not supplied, it returns the rest of the string" },
    "find": { minArgs: 2, maxArgs: 2, snippet: "find(s, sub)", description: "returns the index of the first occurrence of sub in s. -1 if not found. Works only for strings." },
    "replace": { minArgs: 3, maxArgs: 3, snippet: "replace(s, old, new)", description: "replaces occurrences of old with new in s. Mostly for strings but can work with lists and tensors." },
    "dilate": { minArgs: 1, maxArgs: 2, snippet: "dilate(x, kernel)", description: "applies dilation to x. kernel is optional." },
    "erode": { minArgs: 1, maxArgs: 2, snippet: "erode(x, kernel)", description: "applies erosion to x. kernel is size of used matrix." },
    "morph_open": { minArgs: 1, maxArgs: 2, snippet: "morph_open(x, kernel)", description: "applies morphological opening to x. kernel is size of used matrix." },
    "morph_close": { minArgs: 1, maxArgs: 2, snippet: "morph_close(x, kernel)", description: "applies morphological closing to x. kernel is size of used matrix." },
    "rgb_to_oklab": { minArgs: 1, maxArgs: 3, snippet: "rgb_to_oklab(r, g, b)", description: "converts RGB to OKLab. It has 2 modes. Aither 1 or 3 parameters. With 1 parameter it expects last dimension of 3 and with 3 it concatinates them after converting." },
    "rgb_to_cielab": { minArgs: 1, maxArgs: 3, snippet: "rgb_to_cielab(r, g, b)", description: "converts RGB to CIELAB. It has 2 modes. Aither 1 or 3 parameters. With 1 parameter it expects last dimension of 3 and with 3 it concatinates them after converting." },
    "oklab_to_rgb": { minArgs: 1, maxArgs: 3, snippet: "oklab_to_rgb(oklab)", description: "converts OKLab to RGB. It has 2 modes. Aither 1 or 3 parameters. With 1 parameter it expects last dimension of 3 and with 3 it concatinates them after converting." },
    "cielab_to_rgb": { minArgs: 1, maxArgs: 3, snippet: "cielab_to_rgb(cielab)", description: "converts CIELAB to RGB. It has 2 modes. Aither 1 or 3 parameters. With 1 parameter it expects last dimension of 3 and with 3 it concatinates them after converting." },
    "rgb_to_hsv": { minArgs: 1, maxArgs: 4, snippet: "rgb_to_hsv(rgb, degrees)", description: "converts RGB to HSV. It has 2 modes. Aither 1 or 3 parameters. With 1 parameter it expects last dimension of 3 and with 3 it concatinates them after converting. If degrees is specified and nonzero it returns hue as 0-360 instead of 0-1" },
    "hsv_to_rgb": { minArgs: 1, maxArgs: 4, snippet: "hsv_to_rgb(hsv, degrees)", description: "converts HSV to RGB. It has 2 modes. Aither 1 or 3 parameters. With 1 parameter it expects last dimension of 3 and with 3 it concatinates them after converting." },
    "int_to_rgb": { minArgs: 1, maxArgs: 1, snippet: "int_to_rgb(val)", description: "converts an integer to an RGB color. If input is tensor it stacks the resulting R, G and B tensors using last dimension. If It is list, List of lists is returned and if value, 3 long list is returned." },
    "rgb_to_int": { minArgs: 3, maxArgs: 3, snippet: "rgb_to_int(r, g, b)", description: "converts RGB components to an integer It uses last dimension of tensor (or list) as R,G,B if one value. Othervise uses whole thing as channel." },
    "interpolate_linear": { minArgs: 2, maxArgs: 2, snippet: "interpolate_linear(x, y)", description: "performs linear interpolation on X. Assumes that dim 0 is batch and dim 1 = channel" },
    "interpolate_area": { minArgs: 2, maxArgs: 2, snippet: "interpolate_area(x, y)", description: "performs area interpolation X. Assumes that dim 0 is batch and dim 1 = channel" },
    "interpolate_nearest": { minArgs: 2, maxArgs: 2, snippet: "interpolate_nearest(x, y)", description: "performs nearest neighbor interpolation X. Assumes that dim 0 is batch and dim 1 = channel" },
    "interpolate_nearest_exact": { minArgs: 2, maxArgs: 2, snippet: "interpolate_nearest_exact(x, y)", description: "performs nearest neighbor interpolation X. Assumes that dim 0 is batch and dim 1 = channel" },
    "text_image": { minArgs: 3, maxArgs: 9, snippet: "text_image(text, font, size, max_width, weight, rotation_angle, line_spacing, italic, underline)", description: "renders text to an 2D tensor" },
    "as_nested_tensor": { minArgs: 1, maxArgs: 1, snippet: "as_nested_tensor(x)", description: "converts a list to a nested tensor (special object containing tensors of different shapes behaving like a tensor)" },
    "as_nested": { minArgs: 1, maxArgs: 1, snippet: "as_nested(x)", description: "converts a list to a nested tensor (special object containing tensors of different shapes behaving like a tensor)" },
    "svd": { minArgs: 1, maxArgs: 2, snippet: "svd(x, full_matrices)", description: "computes the singular value decomposition of x. Returns a list of 3 tensors: U, S, V such that x = matmul(matmul(U, diagonal_matrix(S,shape(U))), V)" },
    "singular_value_decomposition": { minArgs: 1, maxArgs: 2, snippet: "singular_value_decomposition(x, full_matrices)", description: "computes the singular value decomposition of x. Returns a list of 3 tensors: U, S, V such that x = matmul(matmul(U, diagonal_matrix(S,shape(U))), V)" },
    "diagonal_matrix": { minArgs: 2, maxArgs: 5, snippet: "diagonal_matrix(x, shape, offset, dim1, dim2)", description: "creates a diagonal matrix from x with specified shape. offset is the diagonal offset. dim1 and dim2 are the dimensions to place the diagonal on." },
    "diag": { minArgs: 2, maxArgs: 5, snippet: "diag(x, shape, offset, dim1, dim2)", description: "creates a diagonal matrix from x with specified shape. offset is the diagonal offset. dim1 and dim2 are the dimensions to place the diagonal on." },
    "timestamp": { minArgs: 0, maxArgs: 0, snippet: "timestamp()", description: "returns the current system timestamp" },
    "now": { minArgs: 0, maxArgs: 0, snippet: "now()", description: "returns the current system timestamp" },
    "sort": { minArgs: 1, maxArgs: 3, snippet: "sort(x, desc, dim)", description: "returns a sorted version of x (If input is tensor, it sorts the last dimension)" },
    "argsort": { minArgs: 1, maxArgs: 3, snippet: "argsort(x, desc, dim)", description: "returns the indices that would sort x. desc defaults to ascending and dim defaults to the last dimension." },
    "argmin": { minArgs: 1, maxArgs: 2, snippet: "argmin(x, as_position)", description: "returns the minimum position in flattened x or coordinates as a list when requested" },
    "argmax": { minArgs: 1, maxArgs: 2, snippet: "argmax(x, as_position)", description: "returns the maximum position in flattened x or coordinates as a list when requested" },
    "softmax": { minArgs: 1, maxArgs: 2, snippet: "softmax(x, axis)", description: "applies the softmax function to x (sum of slice == 1.0 and max value <= 1.0). axis defaults to last." },
    "softmin": { minArgs: 1, maxArgs: 2, snippet: "softmin(x, axis)", description: "applies the softmin function to x (same as softmax(-x,[axis])). axis defaults to last." },
    "unique": { minArgs: 1, maxArgs: 1, snippet: "unique(x)", description: "returns the unique elements (sorted, flatened)" },
    "flip": { minArgs: 2, maxArgs: 2, snippet: "flip(x, dims)", description: "reverses the order of elements along the specified dimensions. Works also for text and list with dims=0" },
    "startswith": { minArgs: 2, maxArgs: 2, snippet: "startswith(text, prefix)", description: "returns 1 if text starts with prefix, else 0" },
    "endswith": { minArgs: 2, maxArgs: 2, snippet: "endswith(text, suffix)", description: "returns 1 if text ends with suffix, else 0" },
    "squeeze": { minArgs: 1, maxArgs: 2, snippet: "squeeze(x, dim)", description: "removes size-1 dimensions from tensor x, optionally at dim" },
    "unsqueeze": { minArgs: 2, maxArgs: 2, snippet: "unsqueeze(x, dim)", description: "inserts a size-1 dimension into tensor x at dim" },
    "roll": { minArgs: 2, maxArgs: 3, snippet: "roll(x, shifts, axis)", description: "rolls tensor x along axis" },
    "cov": { minArgs: 2, maxArgs: 2, snippet: "cov(x, y)", description: "computes the covariance matrix of x and y" },
    "corr": { minArgs: 2, maxArgs: 2, snippet: "corr(x, y)", description: "computes the correlation between x and y" },
    "correlation": { minArgs: 2, maxArgs: 2, snippet: "correlation(x, y)", description: "computes the correlation between x and y" },
    "entropy": { minArgs: 1, maxArgs: 1, snippet: "entropy(x)", description: "computes shanon entropy" },
    "crop": { minArgs: 3, maxArgs: 3, snippet: "crop(x, start, size)", description: "crops tensor x. Take size and begin at start. start should be the low corner. The result is at most size (if size is bigger then rest of tensor)." },
    "coords": { minArgs: 2, maxArgs: 3, snippet: "coords(shape, dim, dtype)", description: "generates a tensor with the specified shape whose values are the coordinates of each element along the specified dimension. The dtype can be specified to control the data type of the output tensor." },
    "coordinates": { minArgs: 2, maxArgs: 3, snippet: "coordinates(shape, dim, dtype)", description: "generates a tensor with the specified shape whose values are the coordinates of each element along the specified dimension. The dtype can be specified to control the data type of the output tensor." },
    "noise": { minArgs: 1, maxArgs: 2, snippet: "noise(seed, shape)", description: "generates normally distributed random noise" },
    "randn": { minArgs: 1, maxArgs: 2, snippet: "randn(seed, shape)", description: "generates normally distributed random noise" },
    "random_normal": { minArgs: 1, maxArgs: 2, snippet: "random_normal(seed, shape)", description: "generates normally distributed random noise" },
    "rand": { minArgs: 1, maxArgs: 2, snippet: "rand(seed, shape)", description: "generates uniformly distributed random noise" },
    "randu": { minArgs: 1, maxArgs: 2, snippet: "randu(seed, shape)", description: "generates uniformly distributed random noise" },
    "random_uniform": { minArgs: 1, maxArgs: 2, snippet: "random_uniform(seed, shape)", description: "generates uniformly distributed random noise" },
    "randc": { minArgs: 3, maxArgs: 4, snippet: "randc(seed, median, sigma, shape)", description: "generates Cauchy distributed random values." },
    "random_cauchy": { minArgs: 3, maxArgs: 4, snippet: "random_cauchy(seed, median, sigma, shape)", description: "generates Cauchy distributed random values." },
    "rande": { minArgs: 2, maxArgs: 3, snippet: "rande(seed, lambda, shape)", description: "generates exponentially distributed random values" },
    "random_exponential": { minArgs: 2, maxArgs: 3, snippet: "random_exponential(seed, lambda, shape)", description: "generates exponentially distributed random values" },
    "randln": { minArgs: 3, maxArgs: 4, snippet: "randln(seed, mean, std, shape)", description: "generates log-normally distributed random values." },
    "random_log_normal": { minArgs: 3, maxArgs: 4, snippet: "random_log_normal(seed, mean, std, shape)", description: "generates log-normally distributed random values." },
    "randb": { minArgs: 2, maxArgs: 3, snippet: "randb(seed, probability, shape)", description: "generates Bernoulli distributed random values (0 or 1). Probability can be a tensor" },
    "random_bernoulli": { minArgs: 2, maxArgs: 3, snippet: "random_bernoulli(seed, probability, shape)", description: "generates Bernoulli distributed random values (0 or 1). Probability can be a tensor" },
    "randp": { minArgs: 2, maxArgs: 3, snippet: "randp(seed, lambda, shape)", description: "generates Poisson distributed random values." },
    "random_poisson": { minArgs: 2, maxArgs: 3, snippet: "random_poisson(seed, lambda, shape)", description: "generates Poisson distributed random values." },
    "randg": { minArgs: 3, maxArgs: 4, snippet: "randg(seed, shape_param, scale, shape)", description: "generates Gamma distributed random values." },
    "random_gamma": { minArgs: 3, maxArgs: 4, snippet: "random_gamma(seed, shape_param, scale, shape)", description: "generates Gamma distributed random values." },
    "randbeta": { minArgs: 3, maxArgs: 4, snippet: "randbeta(seed, alpha, beta, shape)", description: "generates Beta distributed random values" },
    "random_beta": { minArgs: 3, maxArgs: 4, snippet: "random_beta(seed, alpha, beta, shape)", description: "generates Beta distributed random values" },
    "randl": { minArgs: 3, maxArgs: 4, snippet: "randl(seed, loc, scale, shape)", description: "generates Laplace distributed random values" },
    "random_laplace": { minArgs: 3, maxArgs: 4, snippet: "random_laplace(seed, loc, scale, shape)", description: "generates Laplace distributed random values" },
    "randgumbel": { minArgs: 3, maxArgs: 4, snippet: "randgumbel(seed, loc, scale, shape)", description: "generates Gumbel distributed random values" },
    "random_gumbel": { minArgs: 3, maxArgs: 4, snippet: "random_gumbel(seed, loc, scale, shape)", description: "generates Gumbel distributed random values" },
    "randw": { minArgs: 3, maxArgs: 4, snippet: "randw(seed, scale, concentration, shape)", description: "generates Weibull distributed random values" },
    "random_weibull": { minArgs: 3, maxArgs: 4, snippet: "random_weibull(seed, scale, concentration, shape)", description: "generates Weibull distributed random values" },
    "randchi2": { minArgs: 2, maxArgs: 3, snippet: "randchi2(seed, df, shape)", description: "generates Chi-squared distributed random values" },
    "random_chi2": { minArgs: 2, maxArgs: 3, snippet: "random_chi2(seed, df, shape)", description: "generates Chi-squared distributed random values" },
    "randt": { minArgs: 2, maxArgs: 3, snippet: "randt(seed, df, shape)", description: "generates Student-t distributed random values" },
    "random_studentt": { minArgs: 2, maxArgs: 3, snippet: "random_studentt(seed, df, shape)", description: "generates Student-t distributed random values" },
    "perlin": { minArgs: 2, maxArgs: 5, snippet: "perlin(seed, scale, octaves, offset, shape)", description: "generates Perlin noise" },
    "perlin_noise": { minArgs: 2, maxArgs: 5, snippet: "perlin_noise(seed, scale, octaves, offset, shape)", description: "generates Perlin noise" },
    "cellular": { minArgs: 2, maxArgs: 5, snippet: "cellular(seed, scale, jitter, offset, shape)", description: "generates Cellular/Voronoi noise" },
    "voronoi": { minArgs: 2, maxArgs: 5, snippet: "voronoi(seed, scale, jitter, offset, shape)", description: "generates Cellular/Voronoi noise" },
    "worley": { minArgs: 2, maxArgs: 5, snippet: "worley(seed, scale, jitter, offset, shape)", description: "generates Cellular/Voronoi noise" },
    "cellular_noise": { minArgs: 2, maxArgs: 5, snippet: "cellular_noise(seed, scale, jitter, offset, shape)", description: "generates Cellular/Voronoi noise" },
    "voronoi_noise": { minArgs: 2, maxArgs: 5, snippet: "voronoi_noise(seed, scale, jitter, offset, shape)", description: "generates Cellular/Voronoi noise" },
    "plasma": { minArgs: 2, maxArgs: 5, snippet: "plasma(seed, scale, octaves, offset, shape)", description: "generates Plasma/Turbulence noise - same as perlin but default octaves 4" },
    "turbulence": { minArgs: 2, maxArgs: 5, snippet: "turbulence(seed, scale, octaves, offset, shape)", description: "generates Plasma/Turbulence noise - same as perlin but default octaves 4" },
    "plasma_noise": { minArgs: 2, maxArgs: 5, snippet: "plasma_noise(seed, scale, octaves, offset, shape)", description: "generates Plasma/Turbulence noise - same as perlin but default octaves 4" },
    "ridged": { minArgs: 2, maxArgs: 5, snippet: "ridged(seed, scale, octaves, offset, shape)", description: "generates ridged multi-fractal noise" },
    "ridged_noise": { minArgs: 2, maxArgs: 5, snippet: "ridged_noise(seed, scale, octaves, offset, shape)", description: "generates ridged multi-fractal noise" },
    "domain_warp": { minArgs: 4, maxArgs: 8, snippet: "domain_warp(seed, scale, warp_scale, warp_strength, octaves, warp_octaves, offset, shape)", description: "generates domain warped noise" },
    "domain_warp_noise": { minArgs: 4, maxArgs: 8, snippet: "domain_warp_noise(seed, scale, warp_scale, warp_strength, octaves, warp_octaves, offset, shape)", description: "generates domain warped noise" },
};
